///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NOP_Commerce
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickEachShoppingSection recording.
    /// </summary>
    [TestModule("f9b16b80-8c21-489f-a8dd-69234e603fb8", ModuleType.Recording, 1)]
    public partial class ClickEachShoppingSection : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NOP_CommerceRepository repository.
        /// </summary>
        public static NOP_CommerceRepository repo = NOP_CommerceRepository.Instance;

        static ClickEachShoppingSection instance = new ClickEachShoppingSection();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickEachShoppingSection()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickEachShoppingSection Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://localhost:8010/login' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://localhost:8010/login", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N1_Computers' at 25;11.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N1_ComputersInfo, new RecordItemIndex(1));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N1_Computers.Click("25;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N2_Electronics' at 62;19.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N2_ElectronicsInfo, new RecordItemIndex(2));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N2_Electronics.Click("62;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N3_Apparel' at 41;20.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N3_ApparelInfo, new RecordItemIndex(3));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N3_Apparel.Click("41;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N4_DigitalDownloads' at 108;16.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N4_DigitalDownloadsInfo, new RecordItemIndex(4));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N4_DigitalDownloads.Click("108;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N5_Books' at 34;20.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N5_BooksInfo, new RecordItemIndex(5));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N5_Books.Click("34;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N6_Jewelry' at 22;16.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N6_JewelryInfo, new RecordItemIndex(6));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N6_Jewelry.Click("22;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.MasterWrapperPage.GoodsMenu.Sections.N7_GiftCards' at 60;17.", repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N7_GiftCardsInfo, new RecordItemIndex(7));
            repo.YourStore.MasterWrapperPage.GoodsMenu.Sections.N7_GiftCards.Click("60;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'YourStore.MasterWrapperPage.GiftCards'.", repo.YourStore.MasterWrapperPage.GiftCardsInfo, new RecordItemIndex(8));
            Validate.Exists(repo.YourStore.MasterWrapperPage.GiftCardsInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
