///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NOP_Commerce
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_InvalidUsername recording.
    /// </summary>
    [TestModule("26cc14b0-dfc9-4568-a132-bade94a865e3", ModuleType.Recording, 1)]
    public partial class Login_InvalidUsername : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NOP_CommerceRepository repository.
        /// </summary>
        public static NOP_CommerceRepository repo = NOP_CommerceRepository.Instance;

        static Login_InvalidUsername instance = new Login_InvalidUsername();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_InvalidUsername()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_InvalidUsername Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://localhost:8010/' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://localhost:8010/", "IE", "", false, false, false, true, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.HomePage.HeaderMenu.LogIn_Changed' at 11;18.", repo.YourStore.HomePage.HeaderMenu.LogIn_ChangedInfo, new RecordItemIndex(1));
            repo.YourStore.HomePage.HeaderMenu.LogIn_Changed.Click("11;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yuijhyujnhujjkjjuikiok'.", new RecordItemIndex(2));
            Keyboard.Press("yuijhyujnhujjkjjuikiok");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.LeftPane.LoginPage.Password' at 181;27.", repo.YourStore.LeftPane.LoginPage.PasswordInfo, new RecordItemIndex(3));
            repo.YourStore.LeftPane.LoginPage.Password.Click("181;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'YourStore.LeftPane.LoginPage.WrongEmail'.", repo.YourStore.LeftPane.LoginPage.WrongEmailInfo, new RecordItemIndex(4));
            Validate.Exists(repo.YourStore.LeftPane.LoginPage.WrongEmailInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.LeftPane.LoginPage.Password' at 151;18.", repo.YourStore.LeftPane.LoginPage.PasswordInfo, new RecordItemIndex(5));
            repo.YourStore.LeftPane.LoginPage.Password.Click("151;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qwer' with focus on 'YourStore.LeftPane.LoginPage.Password'.", repo.YourStore.LeftPane.LoginPage.PasswordInfo, new RecordItemIndex(6));
            repo.YourStore.LeftPane.LoginPage.Password.PressKeys("qwer");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMED' at 59;25.", repo.YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMEDInfo, new RecordItemIndex(7));
            repo.YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMED.Click("59;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMED' at 59;25.", repo.YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMEDInfo, new RecordItemIndex(8));
            repo.YourStore.LeftPane.LoginPage.LoginSection.LoginButton_RENAMED.Click("59;25");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
