///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NOP_Commerce
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NOP_CommerceRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("193dace1-cd92-49b6-8105-f8556e3b7caa")]
    public partial class NOP_CommerceRepository : RepoGenBaseFolder
    {
        static NOP_CommerceRepository instance = new NOP_CommerceRepository();
        NOP_CommerceRepositoryFolders.YourStoreAppFolder _yourstore;

        /// <summary>
        /// Gets the singleton class instance representing the NOP_CommerceRepository element repository.
        /// </summary>
        [RepositoryFolder("193dace1-cd92-49b6-8105-f8556e3b7caa")]
        public static NOP_CommerceRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NOP_CommerceRepository() 
            : base("NOP_CommerceRepository", "/", null, 0, false, "193dace1-cd92-49b6-8105-f8556e3b7caa", ".\\RepositoryImages\\NOP_CommerceRepository193dace1.rximgres")
        {
            _yourstore = new NOP_CommerceRepositoryFolders.YourStoreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("193dace1-cd92-49b6-8105-f8556e3b7caa")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The YourStore folder.
        /// </summary>
        [RepositoryFolder("907e34ab-a20e-4216-9254-da24a75e8963")]
        public virtual NOP_CommerceRepositoryFolders.YourStoreAppFolder YourStore
        {
            get { return _yourstore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class NOP_CommerceRepositoryFolders
    {
        /// <summary>
        /// The YourStoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("907e34ab-a20e-4216-9254-da24a75e8963")]
        public partial class YourStoreAppFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.HomePageFolder _homepage;
            NOP_CommerceRepositoryFolders.MasterWrapperPageFolder _masterwrapperpage;
            NOP_CommerceRepositoryFolders.LeftPaneFolder _leftpane;
            RepoItemInfo _customercurrencyInfo;
            RepoItemInfo _smallsearchtermsInfo;

            /// <summary>
            /// Creates a new YourStore  folder.
            /// </summary>
            public YourStoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("YourStore", "/dom[@domain~'localhost:8010']", parentFolder, 30000, null, false, "907e34ab-a20e-4216-9254-da24a75e8963", "")
            {
                _homepage = new NOP_CommerceRepositoryFolders.HomePageFolder(this);
                _masterwrapperpage = new NOP_CommerceRepositoryFolders.MasterWrapperPageFolder(this);
                _leftpane = new NOP_CommerceRepositoryFolders.LeftPaneFolder(this);
                _customercurrencyInfo = new RepoItemInfo(this, "CustomerCurrency", ".//select[#'customerCurrency']", 30000, null, "95a4d9d5-497e-4919-8cd8-14a7093c7267");
                _smallsearchtermsInfo = new RepoItemInfo(this, "SmallSearchterms", ".//input[#'small-searchterms']", 30000, null, "50b3de69-e6b7-4257-a11a-0bdf80f429ce");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("907e34ab-a20e-4216-9254-da24a75e8963")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("907e34ab-a20e-4216-9254-da24a75e8963")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CustomerCurrency item.
            /// </summary>
            [RepositoryItem("95a4d9d5-497e-4919-8cd8-14a7093c7267")]
            public virtual Ranorex.SelectTag CustomerCurrency
            {
                get
                {
                    return _customercurrencyInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CustomerCurrency item info.
            /// </summary>
            [RepositoryItemInfo("95a4d9d5-497e-4919-8cd8-14a7093c7267")]
            public virtual RepoItemInfo CustomerCurrencyInfo
            {
                get
                {
                    return _customercurrencyInfo;
                }
            }

            /// <summary>
            /// The SmallSearchterms item.
            /// </summary>
            [RepositoryItem("50b3de69-e6b7-4257-a11a-0bdf80f429ce")]
            public virtual Ranorex.InputTag SmallSearchterms
            {
                get
                {
                    return _smallsearchtermsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SmallSearchterms item info.
            /// </summary>
            [RepositoryItemInfo("50b3de69-e6b7-4257-a11a-0bdf80f429ce")]
            public virtual RepoItemInfo SmallSearchtermsInfo
            {
                get
                {
                    return _smallsearchtermsInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("4fe40791-2683-4d8a-a6a1-d345532dc2a9")]
            public virtual NOP_CommerceRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The MasterWrapperPage folder.
            /// </summary>
            [RepositoryFolder("7746d3bb-fd1b-4ce0-8061-85ba5970361f")]
            public virtual NOP_CommerceRepositoryFolders.MasterWrapperPageFolder MasterWrapperPage
            {
                get { return _masterwrapperpage; }
            }

            /// <summary>
            /// The LeftPane folder.
            /// </summary>
            [RepositoryFolder("446b2cd2-76a0-4c31-96ff-721c6e237f14")]
            public virtual NOP_CommerceRepositoryFolders.LeftPaneFolder LeftPane
            {
                get { return _leftpane; }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("4fe40791-2683-4d8a-a6a1-d345532dc2a9")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.HeaderMenuFolder _headermenu;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "4fe40791-2683-4d8a-a6a1-d345532dc2a9", "")
            {
                _headermenu = new NOP_CommerceRepositoryFolders.HeaderMenuFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4fe40791-2683-4d8a-a6a1-d345532dc2a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HeaderMenu folder.
            /// </summary>
            [RepositoryFolder("e9f3d81b-fd9b-4bf8-bc47-1e86e6983d90")]
            public virtual NOP_CommerceRepositoryFolders.HeaderMenuFolder HeaderMenu
            {
                get { return _headermenu; }
            }
        }

        /// <summary>
        /// The HeaderMenuFolder folder.
        /// </summary>
        [RepositoryFolder("e9f3d81b-fd9b-4bf8-bc47-1e86e6983d90")]
        public partial class HeaderMenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _registerInfo;
            RepoItemInfo _login_changedInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _wishlistInfo;

            /// <summary>
            /// Creates a new HeaderMenu  folder.
            /// </summary>
            public HeaderMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("HeaderMenu", "body/div[5]/div[1]/div[1]/div[2]/div[1]/ul", parentFolder, 30000, null, false, "e9f3d81b-fd9b-4bf8-bc47-1e86e6983d90", "")
            {
                _registerInfo = new RepoItemInfo(this, "Register", "li[1]/a[@innertext='Register']", 30000, null, "b48b2c7d-f4ed-41d4-80a0-345526f7823a");
                _login_changedInfo = new RepoItemInfo(this, "LogIn_Changed", "li[2]/a[@innertext='Log in']", 30000, null, "ffa0368b-4d66-4b90-b9dc-3f2f434dcd6d");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "li[2]/a[@innertext='Log out']", 30000, null, "a361c8aa-3c61-4dc9-9077-d25c2ec659f5");
                _wishlistInfo = new RepoItemInfo(this, "Wishlist", "li[3]/a[@href~'^http://localhost:8010/wis']", 30000, null, "8b9d8514-5386-4af9-b004-bbb1e32ce4b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9f3d81b-fd9b-4bf8-bc47-1e86e6983d90")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9f3d81b-fd9b-4bf8-bc47-1e86e6983d90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("b48b2c7d-f4ed-41d4-80a0-345526f7823a")]
            public virtual Ranorex.ATag Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("b48b2c7d-f4ed-41d4-80a0-345526f7823a")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The LogIn_Changed item.
            /// </summary>
            [RepositoryItem("ffa0368b-4d66-4b90-b9dc-3f2f434dcd6d")]
            public virtual Ranorex.ATag LogIn_Changed
            {
                get
                {
                    return _login_changedInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogIn_Changed item info.
            /// </summary>
            [RepositoryItemInfo("ffa0368b-4d66-4b90-b9dc-3f2f434dcd6d")]
            public virtual RepoItemInfo LogIn_ChangedInfo
            {
                get
                {
                    return _login_changedInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("a361c8aa-3c61-4dc9-9077-d25c2ec659f5")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("a361c8aa-3c61-4dc9-9077-d25c2ec659f5")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Wishlist item.
            /// </summary>
            [RepositoryItem("8b9d8514-5386-4af9-b004-bbb1e32ce4b2")]
            public virtual Ranorex.ATag Wishlist
            {
                get
                {
                    return _wishlistInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Wishlist item info.
            /// </summary>
            [RepositoryItemInfo("8b9d8514-5386-4af9-b004-bbb1e32ce4b2")]
            public virtual RepoItemInfo WishlistInfo
            {
                get
                {
                    return _wishlistInfo;
                }
            }
        }

        /// <summary>
        /// The MasterWrapperPageFolder folder.
        /// </summary>
        [RepositoryFolder("7746d3bb-fd1b-4ce0-8061-85ba5970361f")]
        public partial class MasterWrapperPageFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.FooterFolder _footer;
            NOP_CommerceRepositoryFolders.GoodsMenuFolder _goodsmenu;
            RepoItemInfo _atagreadInfo;
            RepoItemInfo _dateofbirthdayInfo;
            RepoItemInfo _dateofbirthmonthInfo;
            RepoItemInfo _dateofbirthyearInfo;
            RepoItemInfo _pictureofadobephotoshopcs4Info;
            RepoItemInfo _registerbuttonInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _giftcardsInfo;
            RepoItemInfo _masterwrapperpageInfo;

            /// <summary>
            /// Creates a new MasterWrapperPage  folder.
            /// </summary>
            public MasterWrapperPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MasterWrapperPage", "body/div[5]", parentFolder, 30000, null, false, "7746d3bb-fd1b-4ce0-8061-85ba5970361f", "")
            {
                _footer = new NOP_CommerceRepositoryFolders.FooterFolder(this);
                _goodsmenu = new NOP_CommerceRepositoryFolders.GoodsMenuFolder(this);
                _atagreadInfo = new RepoItemInfo(this, "ATagRead", "div[3]//form[@action='http://localhost:8010/cart']/div[3]/div[2]/div[3]/span[@innertext~'^I\\ agree\\ with\\ the\\ terms\\ of']/a[@innertext='(read)']", 30000, null, "869e3ce7-172e-40d2-a5d3-921a1e16996a");
                _dateofbirthdayInfo = new RepoItemInfo(this, "DateOfBirthDay", "div[3]//form[@action='http://localhost:8010/register']/div/div[2]/div[1]/div[2]/div[4]/select[@name='DateOfBirthDay']", 30000, null, "b8075f7c-bb21-4f42-919e-fb9248964d3d");
                _dateofbirthmonthInfo = new RepoItemInfo(this, "DateOfBirthMonth", "div[3]//form[@action='http://localhost:8010/register']/div/div[2]/div[1]/div[2]/div[4]/select[@name='DateOfBirthMonth']", 30000, null, "7166419e-f5f2-46f4-b717-4f9b4ce4e6b9");
                _dateofbirthyearInfo = new RepoItemInfo(this, "DateOfBirthYear", "div[3]//form[@action='http://localhost:8010/register']/div/div[2]/div[1]/div[2]/div[4]/select[@name='DateOfBirthYear']", 30000, null, "e40da54e-c106-4283-9acb-fa6c5ae5cd0c");
                _pictureofadobephotoshopcs4Info = new RepoItemInfo(this, "PictureOfAdobePhotoshopCS4", "div[3]/div[2]/div[2]/div/div[2]/div[4]/div/div[1]//a[@title~'^Show\\ details\\ for\\ Adobe\\ Ph']/img[@title~'^Show\\ details\\ for\\ Adobe\\ Ph']", 30000, null, "2877c030-977e-4576-9c04-743f730e1196");
                _registerbuttonInfo = new RepoItemInfo(this, "RegisterButton", "div[3]/div/div/div/div[2]/div[1]/div[1]/div[3]/input[@type='button']", 30000, null, "b7bdcec7-753a-47cc-ac06-d5fe238d15f5");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", "div[3]/div/div/div/div[2]/div[1]/?/?/form[@action='http://localhost:8010/login']/div[3]/input[@type='submit']", 30000, null, "617115b9-04ba-4269-9b3a-68fcf79978e3");
                _giftcardsInfo = new RepoItemInfo(this, "GiftCards", "div[3]/div[2]/div[2]//h1[@innertext='Gift Cards']", 30000, null, "20d3f6e3-6398-4e04-854b-e066df5bae60");
                _masterwrapperpageInfo = new RepoItemInfo(this, "MasterWrapperPage", "", 30000, null, "93b7570f-b391-41aa-bcbb-0e49c2de105e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7746d3bb-fd1b-4ce0-8061-85ba5970361f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7746d3bb-fd1b-4ce0-8061-85ba5970361f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagRead item.
            /// </summary>
            [RepositoryItem("869e3ce7-172e-40d2-a5d3-921a1e16996a")]
            public virtual Ranorex.ATag ATagRead
            {
                get
                {
                    return _atagreadInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagRead item info.
            /// </summary>
            [RepositoryItemInfo("869e3ce7-172e-40d2-a5d3-921a1e16996a")]
            public virtual RepoItemInfo ATagReadInfo
            {
                get
                {
                    return _atagreadInfo;
                }
            }

            /// <summary>
            /// The DateOfBirthDay item.
            /// </summary>
            [RepositoryItem("b8075f7c-bb21-4f42-919e-fb9248964d3d")]
            public virtual Ranorex.SelectTag DateOfBirthDay
            {
                get
                {
                    return _dateofbirthdayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DateOfBirthDay item info.
            /// </summary>
            [RepositoryItemInfo("b8075f7c-bb21-4f42-919e-fb9248964d3d")]
            public virtual RepoItemInfo DateOfBirthDayInfo
            {
                get
                {
                    return _dateofbirthdayInfo;
                }
            }

            /// <summary>
            /// The DateOfBirthMonth item.
            /// </summary>
            [RepositoryItem("7166419e-f5f2-46f4-b717-4f9b4ce4e6b9")]
            public virtual Ranorex.SelectTag DateOfBirthMonth
            {
                get
                {
                    return _dateofbirthmonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DateOfBirthMonth item info.
            /// </summary>
            [RepositoryItemInfo("7166419e-f5f2-46f4-b717-4f9b4ce4e6b9")]
            public virtual RepoItemInfo DateOfBirthMonthInfo
            {
                get
                {
                    return _dateofbirthmonthInfo;
                }
            }

            /// <summary>
            /// The DateOfBirthYear item.
            /// </summary>
            [RepositoryItem("e40da54e-c106-4283-9acb-fa6c5ae5cd0c")]
            public virtual Ranorex.SelectTag DateOfBirthYear
            {
                get
                {
                    return _dateofbirthyearInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DateOfBirthYear item info.
            /// </summary>
            [RepositoryItemInfo("e40da54e-c106-4283-9acb-fa6c5ae5cd0c")]
            public virtual RepoItemInfo DateOfBirthYearInfo
            {
                get
                {
                    return _dateofbirthyearInfo;
                }
            }

            /// <summary>
            /// The PictureOfAdobePhotoshopCS4 item.
            /// </summary>
            [RepositoryItem("2877c030-977e-4576-9c04-743f730e1196")]
            public virtual Ranorex.ImgTag PictureOfAdobePhotoshopCS4
            {
                get
                {
                    return _pictureofadobephotoshopcs4Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The PictureOfAdobePhotoshopCS4 item info.
            /// </summary>
            [RepositoryItemInfo("2877c030-977e-4576-9c04-743f730e1196")]
            public virtual RepoItemInfo PictureOfAdobePhotoshopCS4Info
            {
                get
                {
                    return _pictureofadobephotoshopcs4Info;
                }
            }

            /// <summary>
            /// The RegisterButton item.
            /// </summary>
            [RepositoryItem("b7bdcec7-753a-47cc-ac06-d5fe238d15f5")]
            public virtual Ranorex.InputTag RegisterButton
            {
                get
                {
                    return _registerbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterButton item info.
            /// </summary>
            [RepositoryItemInfo("b7bdcec7-753a-47cc-ac06-d5fe238d15f5")]
            public virtual RepoItemInfo RegisterButtonInfo
            {
                get
                {
                    return _registerbuttonInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("617115b9-04ba-4269-9b3a-68fcf79978e3")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("617115b9-04ba-4269-9b3a-68fcf79978e3")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The GiftCards item.
            /// </summary>
            [RepositoryItem("20d3f6e3-6398-4e04-854b-e066df5bae60")]
            public virtual Ranorex.H1Tag GiftCards
            {
                get
                {
                    return _giftcardsInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The GiftCards item info.
            /// </summary>
            [RepositoryItemInfo("20d3f6e3-6398-4e04-854b-e066df5bae60")]
            public virtual RepoItemInfo GiftCardsInfo
            {
                get
                {
                    return _giftcardsInfo;
                }
            }

            /// <summary>
            /// The MasterWrapperPage item.
            /// </summary>
            [RepositoryItem("93b7570f-b391-41aa-bcbb-0e49c2de105e")]
            public virtual Ranorex.DivTag MasterWrapperPage
            {
                get
                {
                    return _masterwrapperpageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MasterWrapperPage item info.
            /// </summary>
            [RepositoryItemInfo("93b7570f-b391-41aa-bcbb-0e49c2de105e")]
            public virtual RepoItemInfo MasterWrapperPageInfo
            {
                get
                {
                    return _masterwrapperpageInfo;
                }
            }

            /// <summary>
            /// The Footer folder.
            /// </summary>
            [RepositoryFolder("b7a411c4-32fe-4f99-87ff-07e7bd0a2497")]
            public virtual NOP_CommerceRepositoryFolders.FooterFolder Footer
            {
                get { return _footer; }
            }

            /// <summary>
            /// The GoodsMenu folder.
            /// </summary>
            [RepositoryFolder("02b76b59-b72b-47aa-913d-2f9a8da34e0c")]
            public virtual NOP_CommerceRepositoryFolders.GoodsMenuFolder GoodsMenu
            {
                get { return _goodsmenu; }
            }
        }

        /// <summary>
        /// The FooterFolder folder.
        /// </summary>
        [RepositoryFolder("b7a411c4-32fe-4f99-87ff-07e7bd0a2497")]
        public partial class FooterFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.FooterUpperFolder _footerupper;
            NOP_CommerceRepositoryFolders.FooterLowerFolder _footerlower;

            /// <summary>
            /// Creates a new Footer  folder.
            /// </summary>
            public FooterFolder(RepoGenBaseFolder parentFolder) :
                    base("Footer", "div[4]", parentFolder, 30000, null, false, "b7a411c4-32fe-4f99-87ff-07e7bd0a2497", "")
            {
                _footerupper = new NOP_CommerceRepositoryFolders.FooterUpperFolder(this);
                _footerlower = new NOP_CommerceRepositoryFolders.FooterLowerFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7a411c4-32fe-4f99-87ff-07e7bd0a2497")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7a411c4-32fe-4f99-87ff-07e7bd0a2497")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FooterUpper folder.
            /// </summary>
            [RepositoryFolder("28e869ad-dffc-4ee1-b93c-bc91dc5f2656")]
            public virtual NOP_CommerceRepositoryFolders.FooterUpperFolder FooterUpper
            {
                get { return _footerupper; }
            }

            /// <summary>
            /// The FooterLower folder.
            /// </summary>
            [RepositoryFolder("09a4abb3-090e-44e3-8355-7708fb514505")]
            public virtual NOP_CommerceRepositoryFolders.FooterLowerFolder FooterLower
            {
                get { return _footerlower; }
            }
        }

        /// <summary>
        /// The FooterUpperFolder folder.
        /// </summary>
        [RepositoryFolder("28e869ad-dffc-4ee1-b93c-bc91dc5f2656")]
        public partial class FooterUpperFolder : RepoGenBaseFolder
        {
            RepoItemInfo _n1_informationInfo;
            RepoItemInfo _n2_customerserviceInfo;
            RepoItemInfo _n3_myaccountInfo;

            /// <summary>
            /// Creates a new FooterUpper  folder.
            /// </summary>
            public FooterUpperFolder(RepoGenBaseFolder parentFolder) :
                    base("FooterUpper", "div[1]", parentFolder, 30000, null, false, "28e869ad-dffc-4ee1-b93c-bc91dc5f2656", "")
            {
                _n1_informationInfo = new RepoItemInfo(this, "N1_Information", "div[1]", 30000, null, "1846702c-32e3-44fb-b76f-d4c4ddc8c3a3");
                _n2_customerserviceInfo = new RepoItemInfo(this, "N2_CustomerService", "div[2]", 30000, null, "f8f49813-9524-4475-a957-3eb0ac7c98c4");
                _n3_myaccountInfo = new RepoItemInfo(this, "N3_MyAccount", "div[3]", 30000, null, "9a74c3b3-fa75-4c42-8b28-c1078e4113a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28e869ad-dffc-4ee1-b93c-bc91dc5f2656")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28e869ad-dffc-4ee1-b93c-bc91dc5f2656")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The N1_Information item.
            /// </summary>
            [RepositoryItem("1846702c-32e3-44fb-b76f-d4c4ddc8c3a3")]
            public virtual Ranorex.DivTag N1_Information
            {
                get
                {
                    return _n1_informationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The N1_Information item info.
            /// </summary>
            [RepositoryItemInfo("1846702c-32e3-44fb-b76f-d4c4ddc8c3a3")]
            public virtual RepoItemInfo N1_InformationInfo
            {
                get
                {
                    return _n1_informationInfo;
                }
            }

            /// <summary>
            /// The N2_CustomerService item.
            /// </summary>
            [RepositoryItem("f8f49813-9524-4475-a957-3eb0ac7c98c4")]
            public virtual Ranorex.DivTag N2_CustomerService
            {
                get
                {
                    return _n2_customerserviceInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The N2_CustomerService item info.
            /// </summary>
            [RepositoryItemInfo("f8f49813-9524-4475-a957-3eb0ac7c98c4")]
            public virtual RepoItemInfo N2_CustomerServiceInfo
            {
                get
                {
                    return _n2_customerserviceInfo;
                }
            }

            /// <summary>
            /// The N3_MyAccount item.
            /// </summary>
            [RepositoryItem("9a74c3b3-fa75-4c42-8b28-c1078e4113a4")]
            public virtual Ranorex.DivTag N3_MyAccount
            {
                get
                {
                    return _n3_myaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The N3_MyAccount item info.
            /// </summary>
            [RepositoryItemInfo("9a74c3b3-fa75-4c42-8b28-c1078e4113a4")]
            public virtual RepoItemInfo N3_MyAccountInfo
            {
                get
                {
                    return _n3_myaccountInfo;
                }
            }
        }

        /// <summary>
        /// The FooterLowerFolder folder.
        /// </summary>
        [RepositoryFolder("09a4abb3-090e-44e3-8355-7708fb514505")]
        public partial class FooterLowerFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new FooterLower  folder.
            /// </summary>
            public FooterLowerFolder(RepoGenBaseFolder parentFolder) :
                    base("FooterLower", "div[2]", parentFolder, 30000, null, false, "09a4abb3-090e-44e3-8355-7708fb514505", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09a4abb3-090e-44e3-8355-7708fb514505")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09a4abb3-090e-44e3-8355-7708fb514505")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GoodsMenuFolder folder.
        /// </summary>
        [RepositoryFolder("02b76b59-b72b-47aa-913d-2f9a8da34e0c")]
        public partial class GoodsMenuFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.SectionsFolder _sections;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new GoodsMenu  folder.
            /// </summary>
            public GoodsMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("GoodsMenu", "div[2]", parentFolder, 30000, null, false, "02b76b59-b72b-47aa-913d-2f9a8da34e0c", "")
            {
                _sections = new NOP_CommerceRepositoryFolders.SectionsFolder(this);
                _logoutInfo = new RepoItemInfo(this, "LogOut", "div[1]/div[2]/div[1]/ul/li[2]/a[@innertext='Log out']", 30000, null, "93fea851-399f-4649-bfce-1edb50cb54a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("02b76b59-b72b-47aa-913d-2f9a8da34e0c")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("02b76b59-b72b-47aa-913d-2f9a8da34e0c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("93fea851-399f-4649-bfce-1edb50cb54a1")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("93fea851-399f-4649-bfce-1edb50cb54a1")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Sections folder.
            /// </summary>
            [RepositoryFolder("f4b582d0-7410-4af8-b419-9438675aa675")]
            public virtual NOP_CommerceRepositoryFolders.SectionsFolder Sections
            {
                get { return _sections; }
            }
        }

        /// <summary>
        /// The SectionsFolder folder.
        /// </summary>
        [RepositoryFolder("f4b582d0-7410-4af8-b419-9438675aa675")]
        public partial class SectionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _n1_computersInfo;
            RepoItemInfo _n7_giftcardsInfo;
            RepoItemInfo _n6_jewelryInfo;
            RepoItemInfo _n2_electronicsInfo;
            RepoItemInfo _n3_apparelInfo;
            RepoItemInfo _n4_digitaldownloadsInfo;
            RepoItemInfo _n5_booksInfo;

            /// <summary>
            /// Creates a new Sections  folder.
            /// </summary>
            public SectionsFolder(RepoGenBaseFolder parentFolder) :
                    base("Sections", "", parentFolder, 0, null, false, "f4b582d0-7410-4af8-b419-9438675aa675", "")
            {
                _n1_computersInfo = new RepoItemInfo(this, "N1_Computers", "ul[1]/li[1]/a[@innertext='Computers        ']", 30000, null, "78745850-ff63-4b64-a321-ffc961b25168");
                _n7_giftcardsInfo = new RepoItemInfo(this, "N7_GiftCards", "ul[1]/li[7]/a[@innertext='Gift Cards        ']", 30000, null, "52489039-22e3-4d6b-b77f-8cfbddc70bc3");
                _n6_jewelryInfo = new RepoItemInfo(this, "N6_Jewelry", "ul[1]/li[6]/a[@innertext='Jewelry        ']", 30000, null, "2dbb172d-d91a-44d9-ba15-7bc382451ec3");
                _n2_electronicsInfo = new RepoItemInfo(this, "N2_Electronics", "ul[1]/li[2]/a[@innertext='Electronics        ']", 30000, null, "e2ad0df1-e786-4f3e-919f-386873125ec1");
                _n3_apparelInfo = new RepoItemInfo(this, "N3_Apparel", "ul[1]/li[3]/a[@innertext='Apparel        ']", 30000, null, "e7acf0d4-f1d9-4155-ab10-38ceeaed701e");
                _n4_digitaldownloadsInfo = new RepoItemInfo(this, "N4_DigitalDownloads", "ul[1]/li[4]/a[@innertext~'^Digital\\ downloads\\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "2ff2c062-459d-4850-aa90-42c53f621901");
                _n5_booksInfo = new RepoItemInfo(this, "N5_Books", "ul[1]/li[5]/a[@innertext='Books        ']", 30000, null, "7d3fda08-60ac-4f03-83f6-accbfd68f298");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4b582d0-7410-4af8-b419-9438675aa675")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The N1_Computers item.
            /// </summary>
            [RepositoryItem("78745850-ff63-4b64-a321-ffc961b25168")]
            public virtual Ranorex.ATag N1_Computers
            {
                get
                {
                    return _n1_computersInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N1_Computers item info.
            /// </summary>
            [RepositoryItemInfo("78745850-ff63-4b64-a321-ffc961b25168")]
            public virtual RepoItemInfo N1_ComputersInfo
            {
                get
                {
                    return _n1_computersInfo;
                }
            }

            /// <summary>
            /// The N7_GiftCards item.
            /// </summary>
            [RepositoryItem("52489039-22e3-4d6b-b77f-8cfbddc70bc3")]
            public virtual Ranorex.ATag N7_GiftCards
            {
                get
                {
                    return _n7_giftcardsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N7_GiftCards item info.
            /// </summary>
            [RepositoryItemInfo("52489039-22e3-4d6b-b77f-8cfbddc70bc3")]
            public virtual RepoItemInfo N7_GiftCardsInfo
            {
                get
                {
                    return _n7_giftcardsInfo;
                }
            }

            /// <summary>
            /// The N6_Jewelry item.
            /// </summary>
            [RepositoryItem("2dbb172d-d91a-44d9-ba15-7bc382451ec3")]
            public virtual Ranorex.ATag N6_Jewelry
            {
                get
                {
                    return _n6_jewelryInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N6_Jewelry item info.
            /// </summary>
            [RepositoryItemInfo("2dbb172d-d91a-44d9-ba15-7bc382451ec3")]
            public virtual RepoItemInfo N6_JewelryInfo
            {
                get
                {
                    return _n6_jewelryInfo;
                }
            }

            /// <summary>
            /// The N2_Electronics item.
            /// </summary>
            [RepositoryItem("e2ad0df1-e786-4f3e-919f-386873125ec1")]
            public virtual Ranorex.ATag N2_Electronics
            {
                get
                {
                    return _n2_electronicsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N2_Electronics item info.
            /// </summary>
            [RepositoryItemInfo("e2ad0df1-e786-4f3e-919f-386873125ec1")]
            public virtual RepoItemInfo N2_ElectronicsInfo
            {
                get
                {
                    return _n2_electronicsInfo;
                }
            }

            /// <summary>
            /// The N3_Apparel item.
            /// </summary>
            [RepositoryItem("e7acf0d4-f1d9-4155-ab10-38ceeaed701e")]
            public virtual Ranorex.ATag N3_Apparel
            {
                get
                {
                    return _n3_apparelInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N3_Apparel item info.
            /// </summary>
            [RepositoryItemInfo("e7acf0d4-f1d9-4155-ab10-38ceeaed701e")]
            public virtual RepoItemInfo N3_ApparelInfo
            {
                get
                {
                    return _n3_apparelInfo;
                }
            }

            /// <summary>
            /// The N4_DigitalDownloads item.
            /// </summary>
            [RepositoryItem("2ff2c062-459d-4850-aa90-42c53f621901")]
            public virtual Ranorex.ATag N4_DigitalDownloads
            {
                get
                {
                    return _n4_digitaldownloadsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N4_DigitalDownloads item info.
            /// </summary>
            [RepositoryItemInfo("2ff2c062-459d-4850-aa90-42c53f621901")]
            public virtual RepoItemInfo N4_DigitalDownloadsInfo
            {
                get
                {
                    return _n4_digitaldownloadsInfo;
                }
            }

            /// <summary>
            /// The N5_Books item.
            /// </summary>
            [RepositoryItem("7d3fda08-60ac-4f03-83f6-accbfd68f298")]
            public virtual Ranorex.ATag N5_Books
            {
                get
                {
                    return _n5_booksInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The N5_Books item info.
            /// </summary>
            [RepositoryItemInfo("7d3fda08-60ac-4f03-83f6-accbfd68f298")]
            public virtual RepoItemInfo N5_BooksInfo
            {
                get
                {
                    return _n5_booksInfo;
                }
            }
        }

        /// <summary>
        /// The LeftPaneFolder folder.
        /// </summary>
        [RepositoryFolder("446b2cd2-76a0-4c31-96ff-721c6e237f14")]
        public partial class LeftPaneFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.LoginPageFolder _loginpage;

            /// <summary>
            /// Creates a new LeftPane  folder.
            /// </summary>
            public LeftPaneFolder(RepoGenBaseFolder parentFolder) :
                    base("LeftPane", "", parentFolder, 0, null, false, "446b2cd2-76a0-4c31-96ff-721c6e237f14", "")
            {
                _loginpage = new NOP_CommerceRepositoryFolders.LoginPageFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("446b2cd2-76a0-4c31-96ff-721c6e237f14")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("dd5a7994-e4db-4b93-95b8-05d2dd00c296")]
            public virtual NOP_CommerceRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("dd5a7994-e4db-4b93-95b8-05d2dd00c296")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.LoginSectionFolder _loginsection;
            RepoItemInfo _wrongemailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _emailInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 0, null, false, "dd5a7994-e4db-4b93-95b8-05d2dd00c296", "")
            {
                _loginsection = new NOP_CommerceRepositoryFolders.LoginSectionFolder(this);
                _wrongemailInfo = new RepoItemInfo(this, "WrongEmail", "body/div[5]/div[3]//form[@action='/login']/div[2]/div[1]/span/span[@innertext='Wrong email']", 30000, null, "d342c905-8f92-4a0c-88c7-a951fb6a3ddc");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "d9831c49-1270-4f0e-b7df-c62bfdd85e46");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'Email']", 30000, null, "d70c83bd-9642-4b26-bbb9-52bad2afa580");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd5a7994-e4db-4b93-95b8-05d2dd00c296")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WrongEmail item.
            /// </summary>
            [RepositoryItem("d342c905-8f92-4a0c-88c7-a951fb6a3ddc")]
            public virtual Ranorex.SpanTag WrongEmail
            {
                get
                {
                    return _wrongemailInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WrongEmail item info.
            /// </summary>
            [RepositoryItemInfo("d342c905-8f92-4a0c-88c7-a951fb6a3ddc")]
            public virtual RepoItemInfo WrongEmailInfo
            {
                get
                {
                    return _wrongemailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d9831c49-1270-4f0e-b7df-c62bfdd85e46")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d9831c49-1270-4f0e-b7df-c62bfdd85e46")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("d70c83bd-9642-4b26-bbb9-52bad2afa580")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("d70c83bd-9642-4b26-bbb9-52bad2afa580")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The LoginSection folder.
            /// </summary>
            [RepositoryFolder("b4006671-6b47-4d0f-baae-6277ea34fc28")]
            public virtual NOP_CommerceRepositoryFolders.LoginSectionFolder LoginSection
            {
                get { return _loginsection; }
            }
        }

        /// <summary>
        /// The LoginSectionFolder folder.
        /// </summary>
        [RepositoryFolder("b4006671-6b47-4d0f-baae-6277ea34fc28")]
        public partial class LoginSectionFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.LoginFieldsFolder _loginfields;
            RepoItemInfo _loginbutton_renamedInfo;
            RepoItemInfo _aboutloginregistrationInfo;

            /// <summary>
            /// Creates a new LoginSection  folder.
            /// </summary>
            public LoginSectionFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginSection", "body/div[5]/div[3]/div/div/div", parentFolder, 30000, null, false, "b4006671-6b47-4d0f-baae-6277ea34fc28", "")
            {
                _loginfields = new NOP_CommerceRepositoryFolders.LoginFieldsFolder(this);
                _loginbutton_renamedInfo = new RepoItemInfo(this, "LoginButton_RENAMED", "div[2]/div[1]/?/?/form[@action='/login']/div[3]/input[@type='submit']", 30000, null, "2301f540-5998-4986-9209-8d2c31d23574");
                _aboutloginregistrationInfo = new RepoItemInfo(this, "AboutLoginRegistration", "div[2]/div[3]/?/?/h2[@innertext~'^About\\ login\\ /\\ registratio']", 30000, null, "83d64874-1c77-4a84-903a-deee22bbc501");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4006671-6b47-4d0f-baae-6277ea34fc28")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4006671-6b47-4d0f-baae-6277ea34fc28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginButton_RENAMED item.
            /// </summary>
            [RepositoryItem("2301f540-5998-4986-9209-8d2c31d23574")]
            public virtual Ranorex.InputTag LoginButton_RENAMED
            {
                get
                {
                    return _loginbutton_renamedInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton_RENAMED item info.
            /// </summary>
            [RepositoryItemInfo("2301f540-5998-4986-9209-8d2c31d23574")]
            public virtual RepoItemInfo LoginButton_RENAMEDInfo
            {
                get
                {
                    return _loginbutton_renamedInfo;
                }
            }

            /// <summary>
            /// The AboutLoginRegistration item.
            /// </summary>
            [RepositoryItem("83d64874-1c77-4a84-903a-deee22bbc501")]
            public virtual Ranorex.H2Tag AboutLoginRegistration
            {
                get
                {
                    return _aboutloginregistrationInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The AboutLoginRegistration item info.
            /// </summary>
            [RepositoryItemInfo("83d64874-1c77-4a84-903a-deee22bbc501")]
            public virtual RepoItemInfo AboutLoginRegistrationInfo
            {
                get
                {
                    return _aboutloginregistrationInfo;
                }
            }

            /// <summary>
            /// The LoginFields folder.
            /// </summary>
            [RepositoryFolder("80c82350-fd49-48fd-9f18-92b497062125")]
            public virtual NOP_CommerceRepositoryFolders.LoginFieldsFolder LoginFields
            {
                get { return _loginfields; }
            }
        }

        /// <summary>
        /// The LoginFieldsFolder folder.
        /// </summary>
        [RepositoryFolder("80c82350-fd49-48fd-9f18-92b497062125")]
        public partial class LoginFieldsFolder : RepoGenBaseFolder
        {
            NOP_CommerceRepositoryFolders.PasswordFolder _password;
            NOP_CommerceRepositoryFolders.EmailFolder _email;
            NOP_CommerceRepositoryFolders.WarningsFolder _warnings;
            RepoItemInfo _remembermeforgotpasswordInfo;
            RepoItemInfo _forgotpasswordInfo;

            /// <summary>
            /// Creates a new LoginFields  folder.
            /// </summary>
            public LoginFieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginFields", "div[2]/div[1]/?/?/form[@action='/login']/div[2]", parentFolder, 30000, null, false, "80c82350-fd49-48fd-9f18-92b497062125", "")
            {
                _password = new NOP_CommerceRepositoryFolders.PasswordFolder(this);
                _email = new NOP_CommerceRepositoryFolders.EmailFolder(this);
                _warnings = new NOP_CommerceRepositoryFolders.WarningsFolder(this);
                _remembermeforgotpasswordInfo = new RepoItemInfo(this, "RememberMeForgotPassword", "div[3]", 30000, null, "7d53ca6e-63d9-4175-bb23-34e36750c1e0");
                _forgotpasswordInfo = new RepoItemInfo(this, "ForgotPassword", "div[3]/span/a[@innertext='Forgot password?']", 30000, null, "1426cf21-fe4a-4f25-9d2e-0387f2442a35");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80c82350-fd49-48fd-9f18-92b497062125")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80c82350-fd49-48fd-9f18-92b497062125")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RememberMeForgotPassword item.
            /// </summary>
            [RepositoryItem("7d53ca6e-63d9-4175-bb23-34e36750c1e0")]
            public virtual Ranorex.DivTag RememberMeForgotPassword
            {
                get
                {
                    return _remembermeforgotpasswordInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RememberMeForgotPassword item info.
            /// </summary>
            [RepositoryItemInfo("7d53ca6e-63d9-4175-bb23-34e36750c1e0")]
            public virtual RepoItemInfo RememberMeForgotPasswordInfo
            {
                get
                {
                    return _remembermeforgotpasswordInfo;
                }
            }

            /// <summary>
            /// The ForgotPassword item.
            /// </summary>
            [RepositoryItem("1426cf21-fe4a-4f25-9d2e-0387f2442a35")]
            public virtual Ranorex.ATag ForgotPassword
            {
                get
                {
                    return _forgotpasswordInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForgotPassword item info.
            /// </summary>
            [RepositoryItemInfo("1426cf21-fe4a-4f25-9d2e-0387f2442a35")]
            public virtual RepoItemInfo ForgotPasswordInfo
            {
                get
                {
                    return _forgotpasswordInfo;
                }
            }

            /// <summary>
            /// The Password folder.
            /// </summary>
            [RepositoryFolder("5385450a-c029-4b50-b8a7-9d54866f81d3")]
            public virtual NOP_CommerceRepositoryFolders.PasswordFolder Password
            {
                get { return _password; }
            }

            /// <summary>
            /// The Email folder.
            /// </summary>
            [RepositoryFolder("6a4fac73-fc17-4471-b9ca-92c58654019a")]
            public virtual NOP_CommerceRepositoryFolders.EmailFolder Email
            {
                get { return _email; }
            }

            /// <summary>
            /// The Warnings folder.
            /// </summary>
            [RepositoryFolder("cba3c4ca-34df-4e2a-a95f-5a095419fe28")]
            public virtual NOP_CommerceRepositoryFolders.WarningsFolder Warnings
            {
                get { return _warnings; }
            }
        }

        /// <summary>
        /// The PasswordFolder folder.
        /// </summary>
        [RepositoryFolder("5385450a-c029-4b50-b8a7-9d54866f81d3")]
        public partial class PasswordFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Password  folder.
            /// </summary>
            public PasswordFolder(RepoGenBaseFolder parentFolder) :
                    base("Password", "div[2]", parentFolder, 30000, null, false, "5385450a-c029-4b50-b8a7-9d54866f81d3", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5385450a-c029-4b50-b8a7-9d54866f81d3")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5385450a-c029-4b50-b8a7-9d54866f81d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The EmailFolder folder.
        /// </summary>
        [RepositoryFolder("6a4fac73-fc17-4471-b9ca-92c58654019a")]
        public partial class EmailFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Email  folder.
            /// </summary>
            public EmailFolder(RepoGenBaseFolder parentFolder) :
                    base("Email", "div[1]", parentFolder, 30000, null, false, "6a4fac73-fc17-4471-b9ca-92c58654019a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6a4fac73-fc17-4471-b9ca-92c58654019a")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a4fac73-fc17-4471-b9ca-92c58654019a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WarningsFolder folder.
        /// </summary>
        [RepositoryFolder("cba3c4ca-34df-4e2a-a95f-5a095419fe28")]
        public partial class WarningsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _warninglabel_emailnotenteredInfo;
            RepoItemInfo _warninglabel_noaccountfoundInfo;
            RepoItemInfo _warninglabel_incorrectpasswordInfo;
            RepoItemInfo _warninglabel_loginunsuccessfulInfo;

            /// <summary>
            /// Creates a new Warnings  folder.
            /// </summary>
            public WarningsFolder(RepoGenBaseFolder parentFolder) :
                    base("Warnings", "", parentFolder, 0, null, false, "cba3c4ca-34df-4e2a-a95f-5a095419fe28", "")
            {
                _warninglabel_emailnotenteredInfo = new RepoItemInfo(this, "WarningLabel_EmailNotEntered", "div[1]/span/span[@innertext='Please enter your email']", 30000, null, "136b5a37-6842-4a31-9fd2-11f63a6c2349");
                _warninglabel_noaccountfoundInfo = new RepoItemInfo(this, "WarningLabel_NoAccountFound", "?/?/ul/li[@innertext='No customer account found']", 30000, null, "eed2a428-e580-4b84-af74-0d2db1f4991d");
                _warninglabel_incorrectpasswordInfo = new RepoItemInfo(this, "WarningLabel_IncorrectPassword", "?/?/ul/li[@innertext~'^The\\ credentials\\ provided\\ ']", 30000, null, "7260d6bb-7415-4bd7-af80-893bd42a5614");
                _warninglabel_loginunsuccessfulInfo = new RepoItemInfo(this, "WarningLabel_LoginUnsuccessful", "?/?/span[@innertext~'^Login\\ was\\ unsuccessful\\.\\ P']", 30000, null, "81303150-5fe7-4975-952f-36e3eaa047cc");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cba3c4ca-34df-4e2a-a95f-5a095419fe28")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WarningLabel_EmailNotEntered item.
            /// </summary>
            [RepositoryItem("136b5a37-6842-4a31-9fd2-11f63a6c2349")]
            public virtual Ranorex.SpanTag WarningLabel_EmailNotEntered
            {
                get
                {
                    return _warninglabel_emailnotenteredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WarningLabel_EmailNotEntered item info.
            /// </summary>
            [RepositoryItemInfo("136b5a37-6842-4a31-9fd2-11f63a6c2349")]
            public virtual RepoItemInfo WarningLabel_EmailNotEnteredInfo
            {
                get
                {
                    return _warninglabel_emailnotenteredInfo;
                }
            }

            /// <summary>
            /// The WarningLabel_NoAccountFound item.
            /// </summary>
            [RepositoryItem("eed2a428-e580-4b84-af74-0d2db1f4991d")]
            public virtual Ranorex.LiTag WarningLabel_NoAccountFound
            {
                get
                {
                    return _warninglabel_noaccountfoundInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The WarningLabel_NoAccountFound item info.
            /// </summary>
            [RepositoryItemInfo("eed2a428-e580-4b84-af74-0d2db1f4991d")]
            public virtual RepoItemInfo WarningLabel_NoAccountFoundInfo
            {
                get
                {
                    return _warninglabel_noaccountfoundInfo;
                }
            }

            /// <summary>
            /// The WarningLabel_IncorrectPassword item.
            /// </summary>
            [RepositoryItem("7260d6bb-7415-4bd7-af80-893bd42a5614")]
            public virtual Ranorex.LiTag WarningLabel_IncorrectPassword
            {
                get
                {
                    return _warninglabel_incorrectpasswordInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The WarningLabel_IncorrectPassword item info.
            /// </summary>
            [RepositoryItemInfo("7260d6bb-7415-4bd7-af80-893bd42a5614")]
            public virtual RepoItemInfo WarningLabel_IncorrectPasswordInfo
            {
                get
                {
                    return _warninglabel_incorrectpasswordInfo;
                }
            }

            /// <summary>
            /// The WarningLabel_LoginUnsuccessful item.
            /// </summary>
            [RepositoryItem("81303150-5fe7-4975-952f-36e3eaa047cc")]
            public virtual Ranorex.SpanTag WarningLabel_LoginUnsuccessful
            {
                get
                {
                    return _warninglabel_loginunsuccessfulInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WarningLabel_LoginUnsuccessful item info.
            /// </summary>
            [RepositoryItemInfo("81303150-5fe7-4975-952f-36e3eaa047cc")]
            public virtual RepoItemInfo WarningLabel_LoginUnsuccessfulInfo
            {
                get
                {
                    return _warninglabel_loginunsuccessfulInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}