///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SingleArDconfigTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Flow1_Path1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("be02b035-403c-4f1f-aa2c-ab7210b5ffad")]
    public partial class Flow1_Path1Repository : RepoGenBaseFolder
    {
        static Flow1_Path1Repository instance = new Flow1_Path1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Flow1_Path1Repository element repository.
        /// </summary>
        [RepositoryFolder("be02b035-403c-4f1f-aa2c-ab7210b5ffad")]
        public static Flow1_Path1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Flow1_Path1Repository() 
            : base("Flow1_Path1Repository", "/", null, 0, false, "be02b035-403c-4f1f-aa2c-ab7210b5ffad", ".\\RepositoryImages\\Path1Repositorybe02b035.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be02b035-403c-4f1f-aa2c-ab7210b5ffad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class Flow1_Path1RepositoryFolders
    {
    }
#pragma warning restore 0436
}