///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SingleArDconfigTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Flow1_Path2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("39ee496c-9a79-41aa-86bf-e8c566f263ae")]
    public partial class Flow1_Path2Repository : RepoGenBaseFolder
    {
        static Flow1_Path2Repository instance = new Flow1_Path2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Flow1_Path2Repository element repository.
        /// </summary>
        [RepositoryFolder("39ee496c-9a79-41aa-86bf-e8c566f263ae")]
        public static Flow1_Path2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Flow1_Path2Repository() 
            : base("Flow1_Path2Repository", "/", null, 0, false, "39ee496c-9a79-41aa-86bf-e8c566f263ae", ".\\RepositoryImages\\Path2Repository39ee496c.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("39ee496c-9a79-41aa-86bf-e8c566f263ae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class Flow1_Path2RepositoryFolders
    {
    }
#pragma warning restore 0436
}