///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using Ranorex.Core.Reporting;

namespace SingleArDconfigTest
{
    public partial class Flow1_Path1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Path1Usermethod()
        {
        	TestReport.BeginTestCase("Flow1_Path1");
        	
        	TestReport.BeginTestModule("Path1_Block1");
        	Report.Info("Path1 Block1");
        	TestReport.EndTestModule();
        	
        	TestReport.BeginTestModule("Path1_Block2");
        	Report.Info("Path1 Block2");
        	TestReport.EndTestModule();
        	
        	TestReport.EndTestCase();
        }

    }
}
