///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using Ranorex.Core.Reporting;

namespace SingleArDconfigTest
{
    public partial class Flow1_Path2
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Record2Usercode()
        {
        	TestReport.BeginTestCase("Flow1_Path2");
        	
        	TestReport.BeginTestModule("Flow1_Path2_Block1");
        	Report.Info("Flow1 Path2 Block1 (only block)");
        	TestReport.EndTestModule();
        	
        	TestReport.EndTestCase();
        }

    }
}
