///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SingleArDconfigTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SingleArDconfigTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("62e9010b-f791-4bef-89ba-51e8eac460f6")]
    public partial class SingleArDconfigTestRepository : RepoGenBaseFolder
    {
        static SingleArDconfigTestRepository instance = new SingleArDconfigTestRepository();
        SingleArDconfigTestRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the SingleArDconfigTestRepository element repository.
        /// </summary>
        [RepositoryFolder("62e9010b-f791-4bef-89ba-51e8eac460f6")]
        public static SingleArDconfigTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SingleArDconfigTestRepository() 
            : base("SingleArDconfigTestRepository", "/", null, 0, false, "62e9010b-f791-4bef-89ba-51e8eac460f6", ".\\RepositoryImages\\SingleArDconfigTestRepository62e9010b.rximgres")
        {
            _explorer = new SingleArDconfigTestRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62e9010b-f791-4bef-89ba-51e8eac460f6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("8d4410e0-951f-43f6-ae8c-a42129f5ad46")]
        public virtual SingleArDconfigTestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class SingleArDconfigTestRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d4410e0-951f-43f6-ae8c-a42129f5ad46")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;
            RepoItemInfo _nonexistingelementInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 5000, null, true, "8d4410e0-951f-43f6-ae8c-a42129f5ad46", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "?/?/button[@accessiblename='Start']", 30000, null, "5c7a133f-b5ac-4a00-ade6-3cbcd4c82cde");
                _nonexistingelementInfo = new RepoItemInfo(this, "NonExistingElement", "?/?/button[@accessiblename='NotGoingToBeFOund']", 1000, null, "f6bdd880-2f0b-43bc-9b2f-769c742fa843");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d4410e0-951f-43f6-ae8c-a42129f5ad46")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d4410e0-951f-43f6-ae8c-a42129f5ad46")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("5c7a133f-b5ac-4a00-ade6-3cbcd4c82cde")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("5c7a133f-b5ac-4a00-ade6-3cbcd4c82cde")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }

            /// <summary>
            /// The NonExistingElement item.
            /// </summary>
            [RepositoryItem("f6bdd880-2f0b-43bc-9b2f-769c742fa843")]
            public virtual Ranorex.Button NonExistingElement
            {
                get
                {
                    return _nonexistingelementInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NonExistingElement item info.
            /// </summary>
            [RepositoryItemInfo("f6bdd880-2f0b-43bc-9b2f-769c742fa843")]
            public virtual RepoItemInfo NonExistingElementInfo
            {
                get
                {
                    return _nonexistingelementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}