///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SingleArDconfigTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SingleArDconfigTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("62e9010b-f791-4bef-89ba-51e8eac460f6")]
    public partial class SingleArDconfigTestRepository : RepoGenBaseFolder
    {
        static SingleArDconfigTestRepository instance = new SingleArDconfigTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SingleArDconfigTestRepository element repository.
        /// </summary>
        [RepositoryFolder("62e9010b-f791-4bef-89ba-51e8eac460f6")]
        public static SingleArDconfigTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SingleArDconfigTestRepository() 
            : base("SingleArDconfigTestRepository", "/", null, 0, false, "62e9010b-f791-4bef-89ba-51e8eac460f6", ".\\RepositoryImages\\SingleArDconfigTestRepository62e9010b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("62e9010b-f791-4bef-89ba-51e8eac460f6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class SingleArDconfigTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}