///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WEBSTORE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WEBSTORERepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("95b2958e-aca1-489a-a66c-cedf310d3359")]
    public partial class WEBSTORERepository : RepoGenBaseFolder
    {
        static WEBSTORERepository instance = new WEBSTORERepository();

        /// <summary>
        /// Gets the singleton class instance representing the WEBSTORERepository element repository.
        /// </summary>
        [RepositoryFolder("95b2958e-aca1-489a-a66c-cedf310d3359")]
        public static WEBSTORERepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WEBSTORERepository() 
            : base("WEBSTORERepository", "/", null, 0, false, "95b2958e-aca1-489a-a66c-cedf310d3359", ".\\RepositoryImages\\WEBSTORERepository95b2958e.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("95b2958e-aca1-489a-a66c-cedf310d3359")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class WEBSTORERepositoryFolders
    {
    }
#pragma warning restore 0436
}