///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WEBSTORE_RANOREX
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("427a842c-6217-4a85-b482-6cbf2f6787cc", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WEBSTORE_RANOREXRepository repository.
        /// </summary>
        public static WEBSTORE_RANOREXRepository repo = WEBSTORE_RANOREXRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://grid-tools-downloads.com/Will/TMF/index.php' with browser 'firefox' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://grid-tools-downloads.com/Will/TMF/index.php", "firefox", "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='PRODUCT CATALOG') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PRODUCTCATALOG'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PRODUCTCATALOGInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PRODUCTCATALOGInfo, "AccessibleName", "PRODUCT CATALOG");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='-- Select a product --') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, "Text", "-- Select a product --");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox' at 217;21.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, new RecordItemIndex(3));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox.Click("217;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 208;24.", repo.Dropdown.SelfInfo, new RecordItemIndex(4));
            repo.Dropdown.Self.Click("208;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='850.00') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85000'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85000Info, new RecordItemIndex(5));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85000Info, "AccessibleName", "850.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Order Product') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProduct'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProductInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProductInfo, "Text", "Order Product");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProduct' at 26;24.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProductInfo, new RecordItemIndex(7));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.OrderProduct.Click("26;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='DELIVERY LOCATION') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.DELIVERYLOCATION'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.DELIVERYLOCATIONInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.DELIVERYLOCATIONInfo, "AccessibleName", "DELIVERY LOCATION");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email' at 51;18.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.EmailInfo, new RecordItemIndex(9));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email.Click("51;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'guawi01{LShiftKey down}@{LShiftKey up}ca.com{Tab}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.EmailInfo, new RecordItemIndex(10));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email.PressKeys("guawi01{LShiftKey down}@{LShiftKey up}ca.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1' at 34;14.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1Info, new RecordItemIndex(11));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1.Click("34;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'guawi01{LShiftKey down}@{LShiftKey up}ca.com' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1Info, new RecordItemIndex(12));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Email1.PressKeys("guawi01{LShiftKey down}@{LShiftKey up}ca.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name' at 37;10.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.NameInfo, new RecordItemIndex(13));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bill{Tab}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.NameInfo, new RecordItemIndex(14));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name.PressKeys("bill{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text' at 31;24.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TextInfo, new RecordItemIndex(15));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text.Click("31;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10{Space}{RShiftKey down}R{RShiftKey up}oad{Space}{RShiftKey down}R{RShiftKey up}oad{Tab}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TextInfo, new RecordItemIndex(16));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text.PressKeys("10{Space}{RShiftKey down}R{RShiftKey up}oad{Space}{RShiftKey down}R{RShiftKey up}oad{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1' at 27;15.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1Info, new RecordItemIndex(17));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1.Click("27;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey}{LShiftKey down}P{LShiftKey up}lace' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1Info, new RecordItemIndex(18));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text1.PressKeys("{RShiftKey}{LShiftKey down}P{LShiftKey up}lace");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2' at 33;8.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2Info, new RecordItemIndex(19));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}P{LShiftKey up}laceshire' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2Info, new RecordItemIndex(20));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text2.PressKeys("{LShiftKey down}P{LShiftKey up}laceshire");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3' at 22;30.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(21));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.Click("22;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}P{LShiftKey up}{LShiftKey down}L{LShiftKey up}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(22));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("{LShiftKey down}P{LShiftKey up}{LShiftKey down}L{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '7' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(23));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(24));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey up}{LShiftKey down}J{LShiftKey up}98' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(25));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("{LShiftKey up}{LShiftKey down}J{LShiftKey up}98");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox1' at 62;27.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox1Info, new RecordItemIndex(26));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox1.Click("62;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 35;46.", repo.Dropdown.SelfInfo, new RecordItemIndex(27));
            repo.Dropdown.Self.Click("35;46");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save Shipping') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShipping'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShippingInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShippingInfo, "Text", "Save Shipping");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShipping' at 28;8.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShippingInfo, new RecordItemIndex(29));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShipping.Click("28;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3' at 51;27.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(30));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.DoubleClick("51;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3' at 62;12.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(31));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.Click("62;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3' at 62;12.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(32));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.DoubleClick("62;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Please enter a valid UK postcode (OX294TP is a valid UK postcode)') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.PleaseEnterAValidUKPostcodeOX294T'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.PleaseEnterAValidUKPostcodeOX294TInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.PleaseEnterAValidUKPostcodeOX294TInfo, "AccessibleName", "Please enter a valid UK postcode (OX294TP is a valid UK postcode)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3' at 74;11.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(34));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.Click("74;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{LShiftKey down}OX{LShiftKey up}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(35));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("{LControlKey}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{LShiftKey down}OX{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '294{LShiftKey down}TP{LShiftKey up}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3Info, new RecordItemIndex(36));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text3.PressKeys("294{LShiftKey down}TP{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShipping' at 52;15.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShippingInfo, new RecordItemIndex(37));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SaveShipping.Click("52;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='SHIPPING SPECIFICATION') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SHIPPINGSPECIFICATION'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SHIPPINGSPECIFICATIONInfo, new RecordItemIndex(38));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.SHIPPINGSPECIFICATIONInfo, "AccessibleName", "SHIPPING SPECIFICATION");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Total: £855.00 ') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Total85500'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Total85500Info, new RecordItemIndex(39));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Total85500Info, "AccessibleName", "Total: £855.00 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Continue') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Continue'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.ContinueInfo, new RecordItemIndex(40));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.ContinueInfo, "Text", "Continue");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Continue' at 45;7.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.ContinueInfo, new RecordItemIndex(41));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.Continue.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='PAYMENT DETAILS') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PAYMENTDETAILS'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PAYMENTDETAILSInfo, new RecordItemIndex(42));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.PAYMENTDETAILSInfo, "AccessibleName", "PAYMENT DETAILS");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='-- Select Card Type --') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, new RecordItemIndex(43));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, "Text", "-- Select Card Type --");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox' at 148;27.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBoxInfo, new RecordItemIndex(44));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ComboBox.Click("148;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 115;32.", repo.Dropdown.SelfInfo, new RecordItemIndex(45));
            repo.Dropdown.Self.Click("115;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(46));
            Validate.Exists(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1' at 122;11.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(47));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.Click("122;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(48));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.PressKeys("1111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase' at 64;15.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchaseInfo, new RecordItemIndex(49));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase.Click("64;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The Card Number cannot have less that 16 characters. ') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16Info, new RecordItemIndex(50));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16Info, "AccessibleName", "The Card Number cannot have less that 16 characters. ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1' at 84;25.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(51));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.DoubleClick("84;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1' at 84;25.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(52));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.Click("84;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(53));
            Keyboard.PrepareFocus(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, 93, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999999999999' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(54));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.PressKeys("9999999999999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase' at 84;24.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchaseInfo, new RecordItemIndex(55));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase.Click("84;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The Card Number cannot have more that 16 characters. ') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16Info, new RecordItemIndex(56));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCannotHaveLessThat16Info, "AccessibleName", "The Card Number cannot have more that 16 characters. ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1' at 67;22.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(57));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.DoubleClick("67;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(58));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaaaaaaaaaaaaaaa' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(59));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.PressKeys("aaaaaaaaaaaaaaaa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase' at 61;17.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchaseInfo, new RecordItemIndex(60));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase.Click("61;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The card number can only contain numbers.') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCanOnlyContainNumbers'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCanOnlyContainNumbersInfo, new RecordItemIndex(61));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TheCardNumberCanOnlyContainNumbersInfo, "AccessibleName", "The card number can only contain numbers.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1' at 166;26.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(62));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.DoubleClick("166;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111222233334444' with focus on 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1Info, new RecordItemIndex(63));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Name1.PressKeys("1111222233334444");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='857.00') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85700'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85700Info, new RecordItemIndex(64));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.Text85700Info, "AccessibleName", "857.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase' at 95;27.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchaseInfo, new RecordItemIndex(65));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.CompletePurchase.Click("95;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Estimated delivery time - 4.5 days ') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.EstimatedDeliveryTime45Days'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.EstimatedDeliveryTime45DaysInfo, new RecordItemIndex(66));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.EstimatedDeliveryTime45DaysInfo, "AccessibleName", "Estimated delivery time - 4.5 days ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Total cost: 855.00') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TotalCost85500'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TotalCost85500Info, new RecordItemIndex(67));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.TotalCost85500Info, "AccessibleName", "Total cost: 855.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='ORDER FINALISED') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ORDERFINALISED'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ORDERFINALISEDInfo, new RecordItemIndex(68));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ORDERFINALISEDInfo, "AccessibleName", "ORDER FINALISED");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='HOME') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOME'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOMEInfo, new RecordItemIndex(69));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOMEInfo, "Text", "HOME");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='ABOUT') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUT'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUTInfo, new RecordItemIndex(70));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUTInfo, "Text", "ABOUT");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HttpGridToolsDownloadsComWillTMF' at 1256;852.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HttpGridToolsDownloadsComWillTMFInfo, new RecordItemIndex(71));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HttpGridToolsDownloadsComWillTMF.Click("1256;852");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUT1' at 15;11.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUT1Info, new RecordItemIndex(72));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.ABOUT1.Click("15;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='GAME RULES') on item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF.GAMERULES'.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.GAMERULESInfo, new RecordItemIndex(73));
            Validate.Attribute(repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF.GAMERULESInfo, "AccessibleName", "GAME RULES");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOME' at 38;26.", repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOMEInfo, new RecordItemIndex(74));
            repo.MozillaFirefox.HttpGridToolsDownloadsComWillTMF1.HOME.Click("38;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
