///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WEBSTORE_RANOREX
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WEBSTORE_RANOREXRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
    public partial class WEBSTORE_RANOREXRepository : RepoGenBaseFolder
    {
        static WEBSTORE_RANOREXRepository instance = new WEBSTORE_RANOREXRepository();
        WEBSTORE_RANOREXRepositoryFolders.MozillaFirefoxAppFolder _mozillafirefox;
        WEBSTORE_RANOREXRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the WEBSTORE_RANOREXRepository element repository.
        /// </summary>
        [RepositoryFolder("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
        public static WEBSTORE_RANOREXRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WEBSTORE_RANOREXRepository() 
            : base("WEBSTORE_RANOREXRepository", "/", null, 0, false, "065034de-eca3-4561-a3a1-b06d88c4e9a9", ".\\RepositoryImages\\WEBSTORE_RANOREXRepository065034de.rximgres")
        {
            _mozillafirefox = new WEBSTORE_RANOREXRepositoryFolders.MozillaFirefoxAppFolder(this);
            _dropdown = new WEBSTORE_RANOREXRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
        public virtual WEBSTORE_RANOREXRepositoryFolders.MozillaFirefoxAppFolder MozillaFirefox
        {
            get { return _mozillafirefox; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("3822d8cf-2452-481b-886b-8e757896e2f0")]
        public virtual WEBSTORE_RANOREXRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class WEBSTORE_RANOREXRepositoryFolders
    {
        /// <summary>
        /// The MozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
        public partial class MozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMF1Folder _httpgridtoolsdownloadscomwilltmf1;
            WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMFFolder _httpgridtoolsdownloadscomwilltmf;

            /// <summary>
            /// Creates a new MozillaFirefox  folder.
            /// </summary>
            public MozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MozillaFirefox", "/form[@processname='firefox' and @class='MozillaWindowClass' and @instance='1']", parentFolder, 30000, null, true, "36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72", "")
            {
                _httpgridtoolsdownloadscomwilltmf1 = new WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMF1Folder(this);
                _httpgridtoolsdownloadscomwilltmf = new WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMFFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF1 folder.
            /// </summary>
            [RepositoryFolder("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMF1Folder HttpGridToolsDownloadsComWillTMF1
            {
                get { return _httpgridtoolsdownloadscomwilltmf1; }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF folder.
            /// </summary>
            [RepositoryFolder("418ff1e2-4542-4fb4-a3de-00345e2918e0")]
            public virtual WEBSTORE_RANOREXRepositoryFolders.HttpGridToolsDownloadsComWillTMFFolder HttpGridToolsDownloadsComWillTMF
            {
                get { return _httpgridtoolsdownloadscomwilltmf; }
            }
        }

        /// <summary>
        /// The HttpGridToolsDownloadsComWillTMF1Folder folder.
        /// </summary>
        [RepositoryFolder("eadde127-4096-42dc-967a-c90e493136ab")]
        public partial class HttpGridToolsDownloadsComWillTMF1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _httpgridtoolsdownloadscomwilltmfInfo;
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _email1Info;
            RepoItemInfo _name1Info;
            RepoItemInfo _thecardnumbercannothavelessthat16Info;
            RepoItemInfo _thecardnumbercanonlycontainnumbersInfo;
            RepoItemInfo _text85000Info;
            RepoItemInfo _text85700Info;
            RepoItemInfo _nameInfo;
            RepoItemInfo _orderproductInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _text3Info;
            RepoItemInfo _pleaseenteravalidukpostcodeox294tInfo;
            RepoItemInfo _combobox1Info;
            RepoItemInfo _aboutInfo;
            RepoItemInfo _about1Info;
            RepoItemInfo _homeInfo;
            RepoItemInfo _orderfinalisedInfo;
            RepoItemInfo _estimateddeliverytime45daysInfo;
            RepoItemInfo _totalcost85500Info;

            /// <summary>
            /// Creates a new HttpGridToolsDownloadsComWillTMF1  folder.
            /// </summary>
            public HttpGridToolsDownloadsComWillTMF1Folder(RepoGenBaseFolder parentFolder) :
                    base("HttpGridToolsDownloadsComWillTMF1", "container[@accessiblerole='Grouping']//container[@accessiblename~'^http://grid-tools-downloa']", parentFolder, 30000, null, false, "eadde127-4096-42dc-967a-c90e493136ab", "")
            {
                _httpgridtoolsdownloadscomwilltmfInfo = new RepoItemInfo(this, "HttpGridToolsDownloadsComWillTMF", "", 30000, null, "4651ca16-5d91-410e-ab2a-31ee2f7545a4");
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", ".//container[@accessiblerole='Grouping']/element[1]/combobox[@accessiblerole='ComboBox']", 30000, null, "1946b140-35e6-4029-bfbd-48272c769e4a");
                _emailInfo = new RepoItemInfo(this, "Email", ".//container[@accessiblerole='Grouping']/element[1]/text[@accessiblename='Email']", 30000, null, "52d5e7d4-3dda-48d2-88cd-62be1cf1a24f");
                _email1Info = new RepoItemInfo(this, "Email1", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename='Email']", 30000, null, "84998ed8-d795-4e50-8cbb-a510e394bc9d");
                _name1Info = new RepoItemInfo(this, "Name1", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename='Name']", 30000, null, "b840dcdd-31b6-4314-86e5-9f3af335d6bf");
                _thecardnumbercannothavelessthat16Info = new RepoItemInfo(this, "TheCardNumberCannotHaveLessThat16", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename~'^The\\ Card\\ Number\\ cannot\\ ha']", 30000, null, "3b79d7df-68bc-4393-9e10-e36cb4a2cfa0");
                _thecardnumbercanonlycontainnumbersInfo = new RepoItemInfo(this, "TheCardNumberCanOnlyContainNumbers", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename~'^The\\ card\\ number\\ can\\ only\\ ']", 30000, null, "c1666094-c05b-469c-b436-d43d10a9614d");
                _text85000Info = new RepoItemInfo(this, "Text85000", ".//container[@accessiblerole='Grouping']/element[3]/?/?/table[@accessiblerole='Table']/row[@accessiblename='Price 850.00']/?/?/text[@accessiblename='850.00']", 30000, null, "2d4ba1a3-9318-4cba-afcf-8f8de83e0e94");
                _text85700Info = new RepoItemInfo(this, "Text85700", ".//container[@accessiblerole='Grouping']/element[3]/text[@accessiblename='857.00']", 30000, null, "0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd");
                _nameInfo = new RepoItemInfo(this, "Name", ".//container[@accessiblerole='Grouping']/element[3]/text[@accessiblename='Name']", 30000, null, "9c9d1a09-92fd-4aa8-aa76-708ddd2394f8");
                _orderproductInfo = new RepoItemInfo(this, "OrderProduct", ".//container[@accessiblerole='Grouping']/element[4]/button[@accessiblename='Order Product']", 30000, null, "de7ca254-24f3-4200-9b26-6554ba72c563");
                _textInfo = new RepoItemInfo(this, "Text", ".//container[@accessiblerole='Grouping']/element[4]/text[3]", 30000, null, "1af0cf8a-add1-4231-b5f1-30b0b98e54bc");
                _text1Info = new RepoItemInfo(this, "Text1", ".//container[@accessiblerole='Grouping']/element[5]/text[3]", 30000, null, "7676bef3-0cdc-48fa-a1ae-9db4f5374501");
                _text2Info = new RepoItemInfo(this, "Text2", ".//container[@accessiblerole='Grouping']/element[6]/text[3]", 30000, null, "a2356b3e-3868-43fe-98f0-6f472571d288");
                _text3Info = new RepoItemInfo(this, "Text3", ".//container[@accessiblerole='Grouping']/element[7]/text[3]", 30000, null, "7e8ac1cc-aa1b-4317-a64a-96b596860ee4");
                _pleaseenteravalidukpostcodeox294tInfo = new RepoItemInfo(this, "PleaseEnterAValidUKPostcodeOX294T", ".//container[@accessiblerole='Grouping']/element[7]/text[@accessiblename~'^Please\\ enter\\ a\\ valid\\ UK\\ p']", 30000, null, "4ef175d3-3430-4e89-b63c-1b16b5d86570");
                _combobox1Info = new RepoItemInfo(this, "ComboBox1", ".//container[@accessiblerole='Grouping']/element[8]/combobox[@accessiblerole='ComboBox']", 30000, null, "335bac03-6c35-443f-be1d-4b8a96ee6875");
                _aboutInfo = new RepoItemInfo(this, "ABOUT", ".//list[@accessiblerole='List']/listitem[@accessiblename='ABOUT']/link[@accessiblename='ABOUT']", 30000, null, "f535b504-a584-40ec-840f-578657ea562f");
                _about1Info = new RepoItemInfo(this, "ABOUT1", ".//list[@accessiblerole='List']/listitem[@accessiblename='ABOUT']/link[@accessiblename='ABOUT']/text[@accessiblename='ABOUT']", 30000, null, "9f70466a-23cc-4d8b-9348-bde91e67793e");
                _homeInfo = new RepoItemInfo(this, "HOME", ".//list[@accessiblerole='List']/listitem[@accessiblename='HOME']/link[@accessiblename='HOME']", 30000, null, "850b07f3-d174-4144-8d76-fd69e25955be");
                _orderfinalisedInfo = new RepoItemInfo(this, "ORDERFINALISED", "element[2]/element[1]/text[@accessiblename='ORDER FINALISED']", 30000, null, "768b928b-66b4-43f7-969c-e2880441fd91");
                _estimateddeliverytime45daysInfo = new RepoItemInfo(this, "EstimatedDeliveryTime45Days", "element[2]/element[2]/text[@accessiblename~'^Estimated\\ delivery\\ time\\ -']", 30000, null, "0e74daed-82a6-4f0a-bd9e-751f18c1e7d9");
                _totalcost85500Info = new RepoItemInfo(this, "TotalCost85500", "element[2]/element[3]/text[@accessiblename='Total cost: 855.00']", 30000, null, "583399b2-5689-4d80-afeb-9ee93527c50b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF item.
            /// </summary>
            [RepositoryItem("4651ca16-5d91-410e-ab2a-31ee2f7545a4")]
            public virtual Ranorex.Container HttpGridToolsDownloadsComWillTMF
            {
                get
                {
                    return _httpgridtoolsdownloadscomwilltmfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF item info.
            /// </summary>
            [RepositoryItemInfo("4651ca16-5d91-410e-ab2a-31ee2f7545a4")]
            public virtual RepoItemInfo HttpGridToolsDownloadsComWillTMFInfo
            {
                get
                {
                    return _httpgridtoolsdownloadscomwilltmfInfo;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("1946b140-35e6-4029-bfbd-48272c769e4a")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("1946b140-35e6-4029-bfbd-48272c769e4a")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("52d5e7d4-3dda-48d2-88cd-62be1cf1a24f")]
            public virtual Ranorex.Text Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("52d5e7d4-3dda-48d2-88cd-62be1cf1a24f")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Email1 item.
            /// </summary>
            [RepositoryItem("84998ed8-d795-4e50-8cbb-a510e394bc9d")]
            public virtual Ranorex.Text Email1
            {
                get
                {
                    return _email1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Email1 item info.
            /// </summary>
            [RepositoryItemInfo("84998ed8-d795-4e50-8cbb-a510e394bc9d")]
            public virtual RepoItemInfo Email1Info
            {
                get
                {
                    return _email1Info;
                }
            }

            /// <summary>
            /// The Name1 item.
            /// </summary>
            [RepositoryItem("b840dcdd-31b6-4314-86e5-9f3af335d6bf")]
            public virtual Ranorex.Text Name1
            {
                get
                {
                    return _name1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name1 item info.
            /// </summary>
            [RepositoryItemInfo("b840dcdd-31b6-4314-86e5-9f3af335d6bf")]
            public virtual RepoItemInfo Name1Info
            {
                get
                {
                    return _name1Info;
                }
            }

            /// <summary>
            /// The TheCardNumberCannotHaveLessThat16 item.
            /// </summary>
            [RepositoryItem("3b79d7df-68bc-4393-9e10-e36cb4a2cfa0")]
            public virtual Ranorex.Text TheCardNumberCannotHaveLessThat16
            {
                get
                {
                    return _thecardnumbercannothavelessthat16Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TheCardNumberCannotHaveLessThat16 item info.
            /// </summary>
            [RepositoryItemInfo("3b79d7df-68bc-4393-9e10-e36cb4a2cfa0")]
            public virtual RepoItemInfo TheCardNumberCannotHaveLessThat16Info
            {
                get
                {
                    return _thecardnumbercannothavelessthat16Info;
                }
            }

            /// <summary>
            /// The TheCardNumberCanOnlyContainNumbers item.
            /// </summary>
            [RepositoryItem("c1666094-c05b-469c-b436-d43d10a9614d")]
            public virtual Ranorex.Text TheCardNumberCanOnlyContainNumbers
            {
                get
                {
                    return _thecardnumbercanonlycontainnumbersInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TheCardNumberCanOnlyContainNumbers item info.
            /// </summary>
            [RepositoryItemInfo("c1666094-c05b-469c-b436-d43d10a9614d")]
            public virtual RepoItemInfo TheCardNumberCanOnlyContainNumbersInfo
            {
                get
                {
                    return _thecardnumbercanonlycontainnumbersInfo;
                }
            }

            /// <summary>
            /// The Text85000 item.
            /// </summary>
            [RepositoryItem("2d4ba1a3-9318-4cba-afcf-8f8de83e0e94")]
            public virtual Ranorex.Text Text85000
            {
                get
                {
                    return _text85000Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text85000 item info.
            /// </summary>
            [RepositoryItemInfo("2d4ba1a3-9318-4cba-afcf-8f8de83e0e94")]
            public virtual RepoItemInfo Text85000Info
            {
                get
                {
                    return _text85000Info;
                }
            }

            /// <summary>
            /// The Text85700 item.
            /// </summary>
            [RepositoryItem("0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd")]
            public virtual Ranorex.Text Text85700
            {
                get
                {
                    return _text85700Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text85700 item info.
            /// </summary>
            [RepositoryItemInfo("0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd")]
            public virtual RepoItemInfo Text85700Info
            {
                get
                {
                    return _text85700Info;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("9c9d1a09-92fd-4aa8-aa76-708ddd2394f8")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("9c9d1a09-92fd-4aa8-aa76-708ddd2394f8")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The OrderProduct item.
            /// </summary>
            [RepositoryItem("de7ca254-24f3-4200-9b26-6554ba72c563")]
            public virtual Ranorex.Button OrderProduct
            {
                get
                {
                    return _orderproductInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OrderProduct item info.
            /// </summary>
            [RepositoryItemInfo("de7ca254-24f3-4200-9b26-6554ba72c563")]
            public virtual RepoItemInfo OrderProductInfo
            {
                get
                {
                    return _orderproductInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("1af0cf8a-add1-4231-b5f1-30b0b98e54bc")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("1af0cf8a-add1-4231-b5f1-30b0b98e54bc")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("7676bef3-0cdc-48fa-a1ae-9db4f5374501")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("7676bef3-0cdc-48fa-a1ae-9db4f5374501")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("a2356b3e-3868-43fe-98f0-6f472571d288")]
            public virtual Ranorex.Text Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("a2356b3e-3868-43fe-98f0-6f472571d288")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("7e8ac1cc-aa1b-4317-a64a-96b596860ee4")]
            public virtual Ranorex.Text Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("7e8ac1cc-aa1b-4317-a64a-96b596860ee4")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The PleaseEnterAValidUKPostcodeOX294T item.
            /// </summary>
            [RepositoryItem("4ef175d3-3430-4e89-b63c-1b16b5d86570")]
            public virtual Ranorex.Text PleaseEnterAValidUKPostcodeOX294T
            {
                get
                {
                    return _pleaseenteravalidukpostcodeox294tInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PleaseEnterAValidUKPostcodeOX294T item info.
            /// </summary>
            [RepositoryItemInfo("4ef175d3-3430-4e89-b63c-1b16b5d86570")]
            public virtual RepoItemInfo PleaseEnterAValidUKPostcodeOX294TInfo
            {
                get
                {
                    return _pleaseenteravalidukpostcodeox294tInfo;
                }
            }

            /// <summary>
            /// The ComboBox1 item.
            /// </summary>
            [RepositoryItem("335bac03-6c35-443f-be1d-4b8a96ee6875")]
            public virtual Ranorex.ComboBox ComboBox1
            {
                get
                {
                    return _combobox1Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1 item info.
            /// </summary>
            [RepositoryItemInfo("335bac03-6c35-443f-be1d-4b8a96ee6875")]
            public virtual RepoItemInfo ComboBox1Info
            {
                get
                {
                    return _combobox1Info;
                }
            }

            /// <summary>
            /// The ABOUT item.
            /// </summary>
            [RepositoryItem("f535b504-a584-40ec-840f-578657ea562f")]
            public virtual Ranorex.Link ABOUT
            {
                get
                {
                    return _aboutInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The ABOUT item info.
            /// </summary>
            [RepositoryItemInfo("f535b504-a584-40ec-840f-578657ea562f")]
            public virtual RepoItemInfo ABOUTInfo
            {
                get
                {
                    return _aboutInfo;
                }
            }

            /// <summary>
            /// The ABOUT1 item.
            /// </summary>
            [RepositoryItem("9f70466a-23cc-4d8b-9348-bde91e67793e")]
            public virtual Ranorex.Text ABOUT1
            {
                get
                {
                    return _about1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ABOUT1 item info.
            /// </summary>
            [RepositoryItemInfo("9f70466a-23cc-4d8b-9348-bde91e67793e")]
            public virtual RepoItemInfo ABOUT1Info
            {
                get
                {
                    return _about1Info;
                }
            }

            /// <summary>
            /// The HOME item.
            /// </summary>
            [RepositoryItem("850b07f3-d174-4144-8d76-fd69e25955be")]
            public virtual Ranorex.Link HOME
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The HOME item info.
            /// </summary>
            [RepositoryItemInfo("850b07f3-d174-4144-8d76-fd69e25955be")]
            public virtual RepoItemInfo HOMEInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The ORDERFINALISED item.
            /// </summary>
            [RepositoryItem("768b928b-66b4-43f7-969c-e2880441fd91")]
            public virtual Ranorex.Text ORDERFINALISED
            {
                get
                {
                    return _orderfinalisedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ORDERFINALISED item info.
            /// </summary>
            [RepositoryItemInfo("768b928b-66b4-43f7-969c-e2880441fd91")]
            public virtual RepoItemInfo ORDERFINALISEDInfo
            {
                get
                {
                    return _orderfinalisedInfo;
                }
            }

            /// <summary>
            /// The EstimatedDeliveryTime45Days item.
            /// </summary>
            [RepositoryItem("0e74daed-82a6-4f0a-bd9e-751f18c1e7d9")]
            public virtual Ranorex.Text EstimatedDeliveryTime45Days
            {
                get
                {
                    return _estimateddeliverytime45daysInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EstimatedDeliveryTime45Days item info.
            /// </summary>
            [RepositoryItemInfo("0e74daed-82a6-4f0a-bd9e-751f18c1e7d9")]
            public virtual RepoItemInfo EstimatedDeliveryTime45DaysInfo
            {
                get
                {
                    return _estimateddeliverytime45daysInfo;
                }
            }

            /// <summary>
            /// The TotalCost85500 item.
            /// </summary>
            [RepositoryItem("583399b2-5689-4d80-afeb-9ee93527c50b")]
            public virtual Ranorex.Text TotalCost85500
            {
                get
                {
                    return _totalcost85500Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TotalCost85500 item info.
            /// </summary>
            [RepositoryItemInfo("583399b2-5689-4d80-afeb-9ee93527c50b")]
            public virtual RepoItemInfo TotalCost85500Info
            {
                get
                {
                    return _totalcost85500Info;
                }
            }
        }

        /// <summary>
        /// The HttpGridToolsDownloadsComWillTMFFolder folder.
        /// </summary>
        [RepositoryFolder("418ff1e2-4542-4fb4-a3de-00345e2918e0")]
        public partial class HttpGridToolsDownloadsComWillTMFFolder : RepoGenBaseFolder
        {
            RepoItemInfo _deliverylocationInfo;
            RepoItemInfo _gamerulesInfo;
            RepoItemInfo _paymentdetailsInfo;
            RepoItemInfo _productcatalogInfo;
            RepoItemInfo _shippingspecificationInfo;
            RepoItemInfo _completepurchaseInfo;
            RepoItemInfo _saveshippingInfo;
            RepoItemInfo _total85500Info;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new HttpGridToolsDownloadsComWillTMF  folder.
            /// </summary>
            public HttpGridToolsDownloadsComWillTMFFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpGridToolsDownloadsComWillTMF", "container[@accessiblerole='Grouping']/container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename~'^http://grid-tools-downloa']", parentFolder, 30000, null, false, "418ff1e2-4542-4fb4-a3de-00345e2918e0", "")
            {
                _deliverylocationInfo = new RepoItemInfo(this, "DELIVERYLOCATION", ".//text[@accessiblename='DELIVERY LOCATION']", 30000, null, "ee1796a5-c189-490b-ba8a-857f18fb67b5");
                _gamerulesInfo = new RepoItemInfo(this, "GAMERULES", ".//text[@accessiblename='GAME RULES']", 30000, null, "22bcff07-345f-41ef-8a77-c487cbd29418");
                _paymentdetailsInfo = new RepoItemInfo(this, "PAYMENTDETAILS", ".//text[@accessiblename='PAYMENT DETAILS']", 30000, null, "0a52e7a9-1a16-4049-9056-13af83bffa37");
                _productcatalogInfo = new RepoItemInfo(this, "PRODUCTCATALOG", ".//text[@accessiblename='PRODUCT CATALOG']", 30000, null, "ef40e23c-4e46-4e74-82e4-2b26c60bb225");
                _shippingspecificationInfo = new RepoItemInfo(this, "SHIPPINGSPECIFICATION", ".//text[@accessiblename='SHIPPING SPECIFICATION']", 30000, null, "0be90b22-a3f0-4d7d-8763-6706523e1595");
                _completepurchaseInfo = new RepoItemInfo(this, "CompletePurchase", "element[2]/element[2]//button[@accessiblename='Complete Purchase']", 30000, null, "8d98b018-7c02-4b36-882e-c2bbe3638439");
                _saveshippingInfo = new RepoItemInfo(this, "SaveShipping", "element[2]/element[2]//button[@accessiblename='Save Shipping']", 30000, null, "f1faeefc-46df-4328-8301-69bf333f65e5");
                _total85500Info = new RepoItemInfo(this, "Total85500", "element[2]/element[2]/element[@accessiblerole='None']/element[1]/text[@accessiblename='Total: £855.00 ']", 30000, null, "4331229f-3f7d-4aab-855f-f92bf2bb7ae8");
                _continueInfo = new RepoItemInfo(this, "Continue", "element[2]/element[2]/element[@accessiblerole='None']/element[2]/button[@accessiblename='Continue']", 30000, null, "d64453d0-63a2-4082-8ab5-7a9a0edc13de");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("418ff1e2-4542-4fb4-a3de-00345e2918e0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("418ff1e2-4542-4fb4-a3de-00345e2918e0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DELIVERYLOCATION item.
            /// </summary>
            [RepositoryItem("ee1796a5-c189-490b-ba8a-857f18fb67b5")]
            public virtual Ranorex.Text DELIVERYLOCATION
            {
                get
                {
                    return _deliverylocationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DELIVERYLOCATION item info.
            /// </summary>
            [RepositoryItemInfo("ee1796a5-c189-490b-ba8a-857f18fb67b5")]
            public virtual RepoItemInfo DELIVERYLOCATIONInfo
            {
                get
                {
                    return _deliverylocationInfo;
                }
            }

            /// <summary>
            /// The GAMERULES item.
            /// </summary>
            [RepositoryItem("22bcff07-345f-41ef-8a77-c487cbd29418")]
            public virtual Ranorex.Text GAMERULES
            {
                get
                {
                    return _gamerulesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GAMERULES item info.
            /// </summary>
            [RepositoryItemInfo("22bcff07-345f-41ef-8a77-c487cbd29418")]
            public virtual RepoItemInfo GAMERULESInfo
            {
                get
                {
                    return _gamerulesInfo;
                }
            }

            /// <summary>
            /// The PAYMENTDETAILS item.
            /// </summary>
            [RepositoryItem("0a52e7a9-1a16-4049-9056-13af83bffa37")]
            public virtual Ranorex.Text PAYMENTDETAILS
            {
                get
                {
                    return _paymentdetailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PAYMENTDETAILS item info.
            /// </summary>
            [RepositoryItemInfo("0a52e7a9-1a16-4049-9056-13af83bffa37")]
            public virtual RepoItemInfo PAYMENTDETAILSInfo
            {
                get
                {
                    return _paymentdetailsInfo;
                }
            }

            /// <summary>
            /// The PRODUCTCATALOG item.
            /// </summary>
            [RepositoryItem("ef40e23c-4e46-4e74-82e4-2b26c60bb225")]
            public virtual Ranorex.Text PRODUCTCATALOG
            {
                get
                {
                    return _productcatalogInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PRODUCTCATALOG item info.
            /// </summary>
            [RepositoryItemInfo("ef40e23c-4e46-4e74-82e4-2b26c60bb225")]
            public virtual RepoItemInfo PRODUCTCATALOGInfo
            {
                get
                {
                    return _productcatalogInfo;
                }
            }

            /// <summary>
            /// The SHIPPINGSPECIFICATION item.
            /// </summary>
            [RepositoryItem("0be90b22-a3f0-4d7d-8763-6706523e1595")]
            public virtual Ranorex.Text SHIPPINGSPECIFICATION
            {
                get
                {
                    return _shippingspecificationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SHIPPINGSPECIFICATION item info.
            /// </summary>
            [RepositoryItemInfo("0be90b22-a3f0-4d7d-8763-6706523e1595")]
            public virtual RepoItemInfo SHIPPINGSPECIFICATIONInfo
            {
                get
                {
                    return _shippingspecificationInfo;
                }
            }

            /// <summary>
            /// The CompletePurchase item.
            /// </summary>
            [RepositoryItem("8d98b018-7c02-4b36-882e-c2bbe3638439")]
            public virtual Ranorex.Button CompletePurchase
            {
                get
                {
                    return _completepurchaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CompletePurchase item info.
            /// </summary>
            [RepositoryItemInfo("8d98b018-7c02-4b36-882e-c2bbe3638439")]
            public virtual RepoItemInfo CompletePurchaseInfo
            {
                get
                {
                    return _completepurchaseInfo;
                }
            }

            /// <summary>
            /// The SaveShipping item.
            /// </summary>
            [RepositoryItem("f1faeefc-46df-4328-8301-69bf333f65e5")]
            public virtual Ranorex.Button SaveShipping
            {
                get
                {
                    return _saveshippingInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveShipping item info.
            /// </summary>
            [RepositoryItemInfo("f1faeefc-46df-4328-8301-69bf333f65e5")]
            public virtual RepoItemInfo SaveShippingInfo
            {
                get
                {
                    return _saveshippingInfo;
                }
            }

            /// <summary>
            /// The Total85500 item.
            /// </summary>
            [RepositoryItem("4331229f-3f7d-4aab-855f-f92bf2bb7ae8")]
            public virtual Ranorex.Text Total85500
            {
                get
                {
                    return _total85500Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Total85500 item info.
            /// </summary>
            [RepositoryItemInfo("4331229f-3f7d-4aab-855f-f92bf2bb7ae8")]
            public virtual RepoItemInfo Total85500Info
            {
                get
                {
                    return _total85500Info;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("d64453d0-63a2-4082-8ab5-7a9a0edc13de")]
            public virtual Ranorex.Button Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("d64453d0-63a2-4082-8ab5-7a9a0edc13de")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("3822d8cf-2452-481b-886b-8e757896e2f0")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "3822d8cf-2452-481b-886b-8e757896e2f0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3822d8cf-2452-481b-886b-8e757896e2f0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3822d8cf-2452-481b-886b-8e757896e2f0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}