///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Reporting;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SingleArDconfigTest
{
    public partial class Flow1_Path1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        /*
         * Path with 2 blocks/modules, successful 
         */
        public TestResult Path1Usermethod()
        {
        	TestReport.BeginTestCaseContainer("Flow1_Path1");
        	
        	TestResult testResult = TestResult.Skipped;
        	try {
        		TestReport.BeginTestModule("Flow1_Path1_Block1");
	        		// --- BEGIN ARD Blockcode ---
		        	Report.Info("Flow1 Path Block1");
		        	// --- END ARD Blockcode ---
	        	TestReport.EndTestModule();
	        	
	        	TestReport.BeginTestModule("Flow1_Path1_Block2");
	        		// --- BEGIN ARD Blockcode ---
		        	Report.Info("Flow1 Path Block2");
		        	// --- END ARD Blockcode ---
	        	TestReport.EndTestModule();
	        	
	        	testResult = TestResult.Passed;
        	}
			catch (Exception e) {
        		TestReport.EndTestModule();
        		testResult = RanorexCoreReflectionHelper.HandleError(e);
        		TestReport.SaveLocalScreenshotBuffer();
        	}
        	finally {
        		TestReport.BeginTestContainerTeardown();
        		
        		try 
        		{
        			TestReport.BeginTestModule("Flow1_Path2_Teardown");
		        		// --- BEGIN ARD Blockcode ---
		        		Report.Info("There goes the successful Teardown");
		        		// --- END ARD Blockcode ---
	        		TestReport.EndTestModule();
        		}
        		catch (Exception e) {
        			TestReport.EndTestModule();
	                testResult = RanorexCoreReflectionHelper.HandleError(e);
	                TestReport.SaveLocalScreenshotBuffer();
	        	}
        		finally
        		{
        			TestReport.EndTestContainerTeardown();
        			TestReport.EndTestContainer();
        		}
        	}
			return testResult;        	
        }

    }
}
