///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WEBSTORE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("cf83fe52-b621-4611-acf9-f89325d15f53", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WEBSTORERepository repository.
        /// </summary>
        public static WEBSTORERepository repo = WEBSTORERepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://grid-tools-downloads.com/Will/TMF/index.php' with browser 'firefox' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://grid-tools-downloads.com/Will/TMF/index.php", "firefox", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '0' on item 'WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelection'.", repo.WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelectionInfo, new RecordItemIndex(1));
            repo.WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelection.Element.SetAttributeValue("TagValue", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Product Catalog') on item 'WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOG'.", repo.WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, "InnerText", "Product Catalog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page1_Product_Catalog.Button_OrderProduct' at 82;14.", repo.WEBSTORE.Page1_Product_Catalog.Button_OrderProductInfo, new RecordItemIndex(3));
            repo.WEBSTORE.Page1_Product_Catalog.Button_OrderProduct.Click("82;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Delivery Location') on item 'WEBSTORE.Page2_Delivery_Location.Header_DELIVERYLOCATION'.", repo.WEBSTORE.Page2_Delivery_Location.Header_DELIVERYLOCATIONInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.WEBSTORE.Page2_Delivery_Location.Header_DELIVERYLOCATIONInfo, "InnerText", "Delivery Location");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N1_Email' at 60;26.", repo.WEBSTORE.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(5));
            repo.WEBSTORE.Page2_Delivery_Location.N1_Email.Click("60;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'asdf{LShiftKey down}@{LShiftKey up}asdf.com{Tab}' with focus on 'WEBSTORE.Page2_Delivery_Location.N1_Email'.", repo.WEBSTORE.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(6));
            repo.WEBSTORE.Page2_Delivery_Location.N1_Email.PressKeys("asdf{LShiftKey down}@{LShiftKey up}asdf.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail' at 102;10.", repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(7));
            repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail.Click("102;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'asdf{LShiftKey down}@{LShiftKey up}asdf.com{Tab}' with focus on 'WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail'.", repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(8));
            repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail.PressKeys("asdf{LShiftKey down}@{LShiftKey up}asdf.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N3_Name' at 88;16.", repo.WEBSTORE.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(9));
            repo.WEBSTORE.Page2_Delivery_Location.N3_Name.Click("88;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bill{Tab}' with focus on 'WEBSTORE.Page2_Delivery_Location.N3_Name'.", repo.WEBSTORE.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(10));
            repo.WEBSTORE.Page2_Delivery_Location.N3_Name.PressKeys("bill{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N4_AddressLine1' at 85;14.", repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(11));
            repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1.Click("85;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'WEBSTORE.Page2_Delivery_Location.N4_AddressLine1'.", repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(12));
            repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N5_AddressLine2' at 80;17.", repo.WEBSTORE.Page2_Delivery_Location.N5_AddressLine2Info, new RecordItemIndex(13));
            repo.WEBSTORE.Page2_Delivery_Location.N5_AddressLine2.Click("80;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N6_County' at 75;13.", repo.WEBSTORE.Page2_Delivery_Location.N6_CountyInfo, new RecordItemIndex(14));
            repo.WEBSTORE.Page2_Delivery_Location.N6_County.Click("75;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}O{LShiftKey up}xfordshire' with focus on 'WEBSTORE.Page2_Delivery_Location.N6_County'.", repo.WEBSTORE.Page2_Delivery_Location.N6_CountyInfo, new RecordItemIndex(15));
            repo.WEBSTORE.Page2_Delivery_Location.N6_County.PressKeys("{LShiftKey down}O{LShiftKey up}xfordshire");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N7_PostCode' at 73;11.", repo.WEBSTORE.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(16));
            repo.WEBSTORE.Page2_Delivery_Location.N7_PostCode.Click("73;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}OX{LShiftKey up}' with focus on 'WEBSTORE.Page2_Delivery_Location.N7_PostCode'.", repo.WEBSTORE.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(17));
            repo.WEBSTORE.Page2_Delivery_Location.N7_PostCode.PressKeys("{LShiftKey down}OX{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '294{LShiftKey down}TP{LShiftKey up}' with focus on 'WEBSTORE.Page2_Delivery_Location.N7_PostCode'.", repo.WEBSTORE.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(18));
            repo.WEBSTORE.Page2_Delivery_Location.N7_PostCode.PressKeys("294{LShiftKey down}TP{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'England' on item 'WEBSTORE.Page2_Delivery_Location.N8_Country'.", repo.WEBSTORE.Page2_Delivery_Location.N8_CountryInfo, new RecordItemIndex(19));
            repo.WEBSTORE.Page2_Delivery_Location.N8_Country.Element.SetAttributeValue("TagValue", "England");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.Button_SaveShipping' at 51;15.", repo.WEBSTORE.Page2_Delivery_Location.Button_SaveShippingInfo, new RecordItemIndex(20));
            repo.WEBSTORE.Page2_Delivery_Location.Button_SaveShipping.Click("51;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Shipping Specification') on item 'WEBSTORE.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATION'.", repo.WEBSTORE.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATIONInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.WEBSTORE.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATIONInfo, "InnerText", "Shipping Specification");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Total: £855.00 ') on item 'WEBSTORE.Page3_Shipping_Specification.N1_Total'.", repo.WEBSTORE.Page3_Shipping_Specification.N1_TotalInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.WEBSTORE.Page3_Shipping_Specification.N1_TotalInfo, "InnerText", "Total: £855.00 ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page3_Shipping_Specification.Button_Continue' at 55;17.", repo.WEBSTORE.Page3_Shipping_Specification.Button_ContinueInfo, new RecordItemIndex(23));
            repo.WEBSTORE.Page3_Shipping_Specification.Button_Continue.Click("55;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Payment Details') on item 'WEBSTORE.Page4_Payment_Details.Header_PAYMENTDETAILS'.", repo.WEBSTORE.Page4_Payment_Details.Header_PAYMENTDETAILSInfo, new RecordItemIndex(24));
            Validate.Attribute(repo.WEBSTORE.Page4_Payment_Details.Header_PAYMENTDETAILSInfo, "InnerText", "Payment Details");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'AMEX (£2.00 Charge)' on item 'WEBSTORE.Page4_Payment_Details.N1_CardType'.", repo.WEBSTORE.Page4_Payment_Details.N1_CardTypeInfo, new RecordItemIndex(25));
            repo.WEBSTORE.Page4_Payment_Details.N1_CardType.Element.SetAttributeValue("TagValue", "AMEX (£2.00 Charge)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page4_Payment_Details.N2_CardNo' at 96;25.", repo.WEBSTORE.Page4_Payment_Details.N2_CardNoInfo, new RecordItemIndex(26));
            repo.WEBSTORE.Page4_Payment_Details.N2_CardNo.Click("96;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111222233334444' with focus on 'WEBSTORE.Page4_Payment_Details.N2_CardNo'.", repo.WEBSTORE.Page4_Payment_Details.N2_CardNoInfo, new RecordItemIndex(27));
            repo.WEBSTORE.Page4_Payment_Details.N2_CardNo.PressKeys("1111222233334444");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='857.00') on item 'WEBSTORE.TotalAmount'.", repo.WEBSTORE.TotalAmountInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.WEBSTORE.TotalAmountInfo, "InnerText", "857.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page4_Payment_Details.Button_CompletePurchase' at 125;25.", repo.WEBSTORE.Page4_Payment_Details.Button_CompletePurchaseInfo, new RecordItemIndex(29));
            repo.WEBSTORE.Page4_Payment_Details.Button_CompletePurchase.Click("125;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Order Finalised') on item 'WEBSTORE.Page5_Order_Finalised.Header_ORDERFINALISED'.", repo.WEBSTORE.Page5_Order_Finalised.Header_ORDERFINALISEDInfo, new RecordItemIndex(30));
            Validate.Attribute(repo.WEBSTORE.Page5_Order_Finalised.Header_ORDERFINALISEDInfo, "InnerText", "Order Finalised");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page5_Order_Finalised.N1_EstimatedDeliveryTime' at 199;8.", repo.WEBSTORE.Page5_Order_Finalised.N1_EstimatedDeliveryTimeInfo, new RecordItemIndex(31));
            repo.WEBSTORE.Page5_Order_Finalised.N1_EstimatedDeliveryTime.Click("199;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Navigation.About' at 36;9.", repo.WEBSTORE.Navigation.AboutInfo, new RecordItemIndex(32));
            repo.WEBSTORE.Navigation.About.Click("36;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Game Rules') on item 'WEBSTORE.Page_AboutPage.Header_ABOUT'.", repo.WEBSTORE.Page_AboutPage.Header_ABOUTInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.WEBSTORE.Page_AboutPage.Header_ABOUTInfo, "InnerText", "Game Rules");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Navigation.Home' at 60;22.", repo.WEBSTORE.Navigation.HomeInfo, new RecordItemIndex(34));
            repo.WEBSTORE.Navigation.Home.Click("60;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Product Catalog') on item 'WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOG'.", repo.WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, new RecordItemIndex(35));
            Validate.Attribute(repo.WEBSTORE.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, "InnerText", "Product Catalog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='CA WebStore') on item 'WEBSTORE.Navigation.Webstore_Header'.", repo.WEBSTORE.Navigation.Webstore_HeaderInfo, new RecordItemIndex(36));
            Validate.Attribute(repo.WEBSTORE.Navigation.Webstore_HeaderInfo, "InnerText", "CA WebStore");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='For all your everyday needs') on item 'WEBSTORE.Navigation.Webstore_Slogan'.", repo.WEBSTORE.Navigation.Webstore_SloganInfo, new RecordItemIndex(37));
            Validate.Attribute(repo.WEBSTORE.Navigation.Webstore_SloganInfo, "InnerText", "For all your everyday needs");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
