///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WEBSTORE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Test recording.
    /// </summary>
    [TestModule("0f6ad640-fd9a-4869-889c-41db941e8c5a", ModuleType.Recording, 1)]
    public partial class Test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WEBSTORERepository repository.
        /// </summary>
        public static WEBSTORERepository repo = WEBSTORERepository.Instance;

        static Test instance = new Test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://grid-tools-downloads.com/Will/TMF/index.php' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://grid-tools-downloads.com/Will/TMF/index.php", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to '0' on item 'WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelection'.", repo.WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelectionInfo, new RecordItemIndex(1));
            repo.WEBSTORE.Page1_Product_Catalog.ComboBox_ProductSelection.Element.SetAttributeValue("TagValue", "0");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page1_Product_Catalog.Button_OrderProduct' at 99;15.", repo.WEBSTORE.Page1_Product_Catalog.Button_OrderProductInfo, new RecordItemIndex(2));
            repo.WEBSTORE.Page1_Product_Catalog.Button_OrderProduct.Click("99;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N1_Email' at 79;9.", repo.WEBSTORE.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(3));
            repo.WEBSTORE.Page2_Delivery_Location.N1_Email.Click("79;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qfasdfasdf' with focus on 'WEBSTORE.Page2_Delivery_Location.N1_Email'.", repo.WEBSTORE.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(4));
            repo.WEBSTORE.Page2_Delivery_Location.N1_Email.PressKeys("qfasdfasdf");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail' at 44;17.", repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(5));
            repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail.Click("44;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'zxcvzxcvz' with focus on 'WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail'.", repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(6));
            repo.WEBSTORE.Page2_Delivery_Location.N2_ConfirmEmail.PressKeys("zxcvzxcvz");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N4_AddressLine1' at 42;0.", repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(7));
            repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1.Click("42;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qwerq23r' with focus on 'WEBSTORE.Page2_Delivery_Location.N4_AddressLine1'.", repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(8));
            repo.WEBSTORE.Page2_Delivery_Location.N4_AddressLine1.PressKeys("qwerq23r");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.N3_Name' at 55;29.", repo.WEBSTORE.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(9));
            repo.WEBSTORE.Page2_Delivery_Location.N3_Name.Click("55;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '23r23r' with focus on 'WEBSTORE.Page2_Delivery_Location.N3_Name'.", repo.WEBSTORE.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(10));
            repo.WEBSTORE.Page2_Delivery_Location.N3_Name.PressKeys("23r23r");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WEBSTORE.Page2_Delivery_Location.Button_SaveShipping' at 59;10.", repo.WEBSTORE.Page2_Delivery_Location.Button_SaveShippingInfo, new RecordItemIndex(11));
            repo.WEBSTORE.Page2_Delivery_Location.Button_SaveShipping.Click("59;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
