///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WEBSTORE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WEBSTORERepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
    public partial class WEBSTORERepository : RepoGenBaseFolder
    {
        static WEBSTORERepository instance = new WEBSTORERepository();
        WEBSTORERepositoryFolders.MozillaFirefoxAppFolder _mozillafirefox;
        WEBSTORERepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the WEBSTORERepository element repository.
        /// </summary>
        [RepositoryFolder("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
        public static WEBSTORERepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WEBSTORERepository() 
            : base("WEBSTORERepository", "/", null, 0, false, "065034de-eca3-4561-a3a1-b06d88c4e9a9", ".\\RepositoryImages\\WEBSTORERepository065034de.rximgres")
        {
            _mozillafirefox = new WEBSTORERepositoryFolders.MozillaFirefoxAppFolder(this);
            _dropdown = new WEBSTORERepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("065034de-eca3-4561-a3a1-b06d88c4e9a9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
        public virtual WEBSTORERepositoryFolders.MozillaFirefoxAppFolder MozillaFirefox
        {
            get { return _mozillafirefox; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("3822d8cf-2452-481b-886b-8e757896e2f0")]
        public virtual WEBSTORERepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class WEBSTORERepositoryFolders
    {
        /// <summary>
        /// The MozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
        public partial class MozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            WEBSTORERepositoryFolders.WebStoreFolder _webstore;

            /// <summary>
            /// Creates a new MozillaFirefox  folder.
            /// </summary>
            public MozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MozillaFirefox", "/form[@title='Mozilla Firefox']", parentFolder, 30000, null, true, "36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72", "")
            {
                _webstore = new WEBSTORERepositoryFolders.WebStoreFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("36d402c8-9b5f-4e50-ae16-d6ffdc4e7e72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebStore folder.
            /// </summary>
            [RepositoryFolder("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual WEBSTORERepositoryFolders.WebStoreFolder WebStore
            {
                get { return _webstore; }
            }
        }

        /// <summary>
        /// The WebStoreFolder folder.
        /// </summary>
        [RepositoryFolder("eadde127-4096-42dc-967a-c90e493136ab")]
        public partial class WebStoreFolder : RepoGenBaseFolder
        {
            WEBSTORERepositoryFolders.Page1_Product_CatalogFolder _page1_product_catalog;
            WEBSTORERepositoryFolders.Page2_Delivery_LocationFolder _page2_delivery_location;
            WEBSTORERepositoryFolders.Page3_Shipping_SpecificationFolder _page3_shipping_specification;
            WEBSTORERepositoryFolders.Page4_Payment_DetailsFolder _page4_payment_details;
            WEBSTORERepositoryFolders.Page5_Order_FinalisedFolder _page5_order_finalised;
            WEBSTORERepositoryFolders.Page_AboutPageFolder _page_aboutpage;
            RepoItemInfo _httpgridtoolsdownloadscomwilltmfInfo;
            RepoItemInfo _aboutInfo;
            RepoItemInfo _about1Info;
            RepoItemInfo _homeInfo;
            RepoItemInfo _text85000Info;

            /// <summary>
            /// Creates a new WebStore  folder.
            /// </summary>
            public WebStoreFolder(RepoGenBaseFolder parentFolder) :
                    base("WebStore", "container[@accessiblerole='Grouping']//container[@accessiblename~'^http://grid-tools-downloa']", parentFolder, 30000, null, false, "eadde127-4096-42dc-967a-c90e493136ab", "")
            {
                _page1_product_catalog = new WEBSTORERepositoryFolders.Page1_Product_CatalogFolder(this);
                _page2_delivery_location = new WEBSTORERepositoryFolders.Page2_Delivery_LocationFolder(this);
                _page3_shipping_specification = new WEBSTORERepositoryFolders.Page3_Shipping_SpecificationFolder(this);
                _page4_payment_details = new WEBSTORERepositoryFolders.Page4_Payment_DetailsFolder(this);
                _page5_order_finalised = new WEBSTORERepositoryFolders.Page5_Order_FinalisedFolder(this);
                _page_aboutpage = new WEBSTORERepositoryFolders.Page_AboutPageFolder(this);
                _httpgridtoolsdownloadscomwilltmfInfo = new RepoItemInfo(this, "HttpGridToolsDownloadsComWillTMF", "", 30000, null, "4651ca16-5d91-410e-ab2a-31ee2f7545a4");
                _aboutInfo = new RepoItemInfo(this, "ABOUT", ".//list[@accessiblerole='List']/listitem[@accessiblename='ABOUT']/link[@accessiblename='ABOUT']", 30000, null, "f535b504-a584-40ec-840f-578657ea562f");
                _about1Info = new RepoItemInfo(this, "ABOUT1", ".//list[@accessiblerole='List']/listitem[@accessiblename='ABOUT']/link[@accessiblename='ABOUT']/text[@accessiblename='ABOUT']", 30000, null, "9f70466a-23cc-4d8b-9348-bde91e67793e");
                _homeInfo = new RepoItemInfo(this, "HOME", ".//list[@accessiblerole='List']/listitem[@accessiblename='HOME']/link[@accessiblename='HOME']", 30000, null, "850b07f3-d174-4144-8d76-fd69e25955be");
                _text85000Info = new RepoItemInfo(this, "Text85000", ".//container[@accessiblerole='Grouping']/element[3]/?/?/table[@accessiblerole='Table']/row[@accessiblename='Price 850.00']/?/?/text[@accessiblename='850.00']", 30000, null, "2d4ba1a3-9318-4cba-afcf-8f8de83e0e94");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eadde127-4096-42dc-967a-c90e493136ab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF item.
            /// </summary>
            [RepositoryItem("4651ca16-5d91-410e-ab2a-31ee2f7545a4")]
            public virtual Ranorex.Container HttpGridToolsDownloadsComWillTMF
            {
                get
                {
                    return _httpgridtoolsdownloadscomwilltmfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The HttpGridToolsDownloadsComWillTMF item info.
            /// </summary>
            [RepositoryItemInfo("4651ca16-5d91-410e-ab2a-31ee2f7545a4")]
            public virtual RepoItemInfo HttpGridToolsDownloadsComWillTMFInfo
            {
                get
                {
                    return _httpgridtoolsdownloadscomwilltmfInfo;
                }
            }

            /// <summary>
            /// The ABOUT item.
            /// </summary>
            [RepositoryItem("f535b504-a584-40ec-840f-578657ea562f")]
            public virtual Ranorex.Link ABOUT
            {
                get
                {
                    return _aboutInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The ABOUT item info.
            /// </summary>
            [RepositoryItemInfo("f535b504-a584-40ec-840f-578657ea562f")]
            public virtual RepoItemInfo ABOUTInfo
            {
                get
                {
                    return _aboutInfo;
                }
            }

            /// <summary>
            /// The ABOUT1 item.
            /// </summary>
            [RepositoryItem("9f70466a-23cc-4d8b-9348-bde91e67793e")]
            public virtual Ranorex.Text ABOUT1
            {
                get
                {
                    return _about1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ABOUT1 item info.
            /// </summary>
            [RepositoryItemInfo("9f70466a-23cc-4d8b-9348-bde91e67793e")]
            public virtual RepoItemInfo ABOUT1Info
            {
                get
                {
                    return _about1Info;
                }
            }

            /// <summary>
            /// The HOME item.
            /// </summary>
            [RepositoryItem("850b07f3-d174-4144-8d76-fd69e25955be")]
            public virtual Ranorex.Link HOME
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The HOME item info.
            /// </summary>
            [RepositoryItemInfo("850b07f3-d174-4144-8d76-fd69e25955be")]
            public virtual RepoItemInfo HOMEInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The Text85000 item.
            /// </summary>
            [RepositoryItem("2d4ba1a3-9318-4cba-afcf-8f8de83e0e94")]
            public virtual Ranorex.Text Text85000
            {
                get
                {
                    return _text85000Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text85000 item info.
            /// </summary>
            [RepositoryItemInfo("2d4ba1a3-9318-4cba-afcf-8f8de83e0e94")]
            public virtual RepoItemInfo Text85000Info
            {
                get
                {
                    return _text85000Info;
                }
            }

            /// <summary>
            /// The Page1_Product_Catalog folder.
            /// </summary>
            [RepositoryFolder("f3a1297f-0782-4884-8a40-32b45a15520d")]
            public virtual WEBSTORERepositoryFolders.Page1_Product_CatalogFolder Page1_Product_Catalog
            {
                get { return _page1_product_catalog; }
            }

            /// <summary>
            /// The Page2_Delivery_Location folder.
            /// </summary>
            [RepositoryFolder("82dc6bbf-1bfd-4fab-b35b-8eeade861cb7")]
            public virtual WEBSTORERepositoryFolders.Page2_Delivery_LocationFolder Page2_Delivery_Location
            {
                get { return _page2_delivery_location; }
            }

            /// <summary>
            /// The Page3_Shipping_Specification folder.
            /// </summary>
            [RepositoryFolder("8240971d-4b89-46b0-8563-1dcf082fcbda")]
            public virtual WEBSTORERepositoryFolders.Page3_Shipping_SpecificationFolder Page3_Shipping_Specification
            {
                get { return _page3_shipping_specification; }
            }

            /// <summary>
            /// The Page4_Payment_Details folder.
            /// </summary>
            [RepositoryFolder("20c9cd1b-9237-4c21-8854-7cee4a220dbc")]
            public virtual WEBSTORERepositoryFolders.Page4_Payment_DetailsFolder Page4_Payment_Details
            {
                get { return _page4_payment_details; }
            }

            /// <summary>
            /// The Page5_Order_Finalised folder.
            /// </summary>
            [RepositoryFolder("b80788e5-e019-415e-b9a8-6349a4b942af")]
            public virtual WEBSTORERepositoryFolders.Page5_Order_FinalisedFolder Page5_Order_Finalised
            {
                get { return _page5_order_finalised; }
            }

            /// <summary>
            /// The Page_AboutPage folder.
            /// </summary>
            [RepositoryFolder("6bb127cd-365b-4549-834e-b301159eca55")]
            public virtual WEBSTORERepositoryFolders.Page_AboutPageFolder Page_AboutPage
            {
                get { return _page_aboutpage; }
            }
        }

        /// <summary>
        /// The Page1_Product_CatalogFolder folder.
        /// </summary>
        [RepositoryFolder("f3a1297f-0782-4884-8a40-32b45a15520d")]
        public partial class Page1_Product_CatalogFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button_orderproductInfo;
            RepoItemInfo _header_productcatalogInfo;

            /// <summary>
            /// Creates a new Page1_Product_Catalog  folder.
            /// </summary>
            public Page1_Product_CatalogFolder(RepoGenBaseFolder parentFolder) :
                    base("Page1_Product_Catalog", "", parentFolder, 0, null, false, "f3a1297f-0782-4884-8a40-32b45a15520d", "")
            {
                _button_orderproductInfo = new RepoItemInfo(this, "Button_OrderProduct", ".//container[@accessiblerole='Grouping']/element[4]/button[@accessiblename='Order Product']", 30000, null, "de7ca254-24f3-4200-9b26-6554ba72c563");
                _header_productcatalogInfo = new RepoItemInfo(this, "Header_PRODUCTCATALOG", ".//text[@accessiblename='PRODUCT CATALOG']", 30000, null, "ef40e23c-4e46-4e74-82e4-2b26c60bb225");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f3a1297f-0782-4884-8a40-32b45a15520d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button_OrderProduct item.
            /// </summary>
            [RepositoryItem("de7ca254-24f3-4200-9b26-6554ba72c563")]
            public virtual Ranorex.Button Button_OrderProduct
            {
                get
                {
                    return _button_orderproductInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_OrderProduct item info.
            /// </summary>
            [RepositoryItemInfo("de7ca254-24f3-4200-9b26-6554ba72c563")]
            public virtual RepoItemInfo Button_OrderProductInfo
            {
                get
                {
                    return _button_orderproductInfo;
                }
            }

            /// <summary>
            /// The Header_PRODUCTCATALOG item.
            /// </summary>
            [RepositoryItem("ef40e23c-4e46-4e74-82e4-2b26c60bb225")]
            public virtual Ranorex.Text Header_PRODUCTCATALOG
            {
                get
                {
                    return _header_productcatalogInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header_PRODUCTCATALOG item info.
            /// </summary>
            [RepositoryItemInfo("ef40e23c-4e46-4e74-82e4-2b26c60bb225")]
            public virtual RepoItemInfo Header_PRODUCTCATALOGInfo
            {
                get
                {
                    return _header_productcatalogInfo;
                }
            }
        }

        /// <summary>
        /// The Page2_Delivery_LocationFolder folder.
        /// </summary>
        [RepositoryFolder("82dc6bbf-1bfd-4fab-b35b-8eeade861cb7")]
        public partial class Page2_Delivery_LocationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _n7_postcodeInfo;
            RepoItemInfo _n4_addressline1Info;
            RepoItemInfo _n6_countyInfo;
            RepoItemInfo _n5_addressline2Info;
            RepoItemInfo _n3_nameInfo;
            RepoItemInfo _n2_confirmemailInfo;
            RepoItemInfo _n1_emailInfo;
            RepoItemInfo _warning_postcodeinvalidInfo;
            RepoItemInfo _n8_countryInfo;
            RepoItemInfo _button_saveshippingInfo;
            RepoItemInfo _header_deliverylocationInfo;

            /// <summary>
            /// Creates a new Page2_Delivery_Location  folder.
            /// </summary>
            public Page2_Delivery_LocationFolder(RepoGenBaseFolder parentFolder) :
                    base("Page2_Delivery_Location", "", parentFolder, 0, null, false, "82dc6bbf-1bfd-4fab-b35b-8eeade861cb7", "")
            {
                _n7_postcodeInfo = new RepoItemInfo(this, "N7_PostCode", ".//container[@accessiblerole='Grouping']/element[7]/text[3]", 30000, null, "7e8ac1cc-aa1b-4317-a64a-96b596860ee4");
                _n4_addressline1Info = new RepoItemInfo(this, "N4_AddressLine1", ".//container[@accessiblerole='Grouping']/element[4]/text[3]", 30000, null, "1af0cf8a-add1-4231-b5f1-30b0b98e54bc");
                _n6_countyInfo = new RepoItemInfo(this, "N6_County", ".//container[@accessiblerole='Grouping']/element[6]/text[3]", 30000, null, "a2356b3e-3868-43fe-98f0-6f472571d288");
                _n5_addressline2Info = new RepoItemInfo(this, "N5_AddressLine2", ".//container[@accessiblerole='Grouping']/element[5]/text[3]", 30000, null, "7676bef3-0cdc-48fa-a1ae-9db4f5374501");
                _n3_nameInfo = new RepoItemInfo(this, "N3_Name", ".//container[@accessiblerole='Grouping']/element[3]/text[@accessiblename='Name']", 30000, null, "9c9d1a09-92fd-4aa8-aa76-708ddd2394f8");
                _n2_confirmemailInfo = new RepoItemInfo(this, "N2_ConfirmEmail", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename='Email']", 30000, null, "84998ed8-d795-4e50-8cbb-a510e394bc9d");
                _n1_emailInfo = new RepoItemInfo(this, "N1_Email", ".//container[@accessiblerole='Grouping']/element[1]/text[@accessiblename='Email']", 30000, null, "52d5e7d4-3dda-48d2-88cd-62be1cf1a24f");
                _warning_postcodeinvalidInfo = new RepoItemInfo(this, "Warning_PostcodeInvalid", ".//container[@accessiblerole='Grouping']/element[7]/text[@accessiblename~'^Please\\ enter\\ a\\ valid\\ UK\\ p']", 30000, null, "4ef175d3-3430-4e89-b63c-1b16b5d86570");
                _n8_countryInfo = new RepoItemInfo(this, "N8_Country", ".//container[@accessiblerole='Grouping']/element[8]/combobox[@accessiblerole='ComboBox']", 30000, null, "335bac03-6c35-443f-be1d-4b8a96ee6875");
                _button_saveshippingInfo = new RepoItemInfo(this, "Button_SaveShipping", "element[2]/element[2]//button[@accessiblename='Save Shipping']", 30000, null, "f1faeefc-46df-4328-8301-69bf333f65e5");
                _header_deliverylocationInfo = new RepoItemInfo(this, "Header_DELIVERYLOCATION", ".//text[@accessiblename='DELIVERY LOCATION']", 30000, null, "ee1796a5-c189-490b-ba8a-857f18fb67b5");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("82dc6bbf-1bfd-4fab-b35b-8eeade861cb7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The N7_PostCode item.
            /// </summary>
            [RepositoryItem("7e8ac1cc-aa1b-4317-a64a-96b596860ee4")]
            public virtual Ranorex.Text N7_PostCode
            {
                get
                {
                    return _n7_postcodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N7_PostCode item info.
            /// </summary>
            [RepositoryItemInfo("7e8ac1cc-aa1b-4317-a64a-96b596860ee4")]
            public virtual RepoItemInfo N7_PostCodeInfo
            {
                get
                {
                    return _n7_postcodeInfo;
                }
            }

            /// <summary>
            /// The N4_AddressLine1 item.
            /// </summary>
            [RepositoryItem("1af0cf8a-add1-4231-b5f1-30b0b98e54bc")]
            public virtual Ranorex.Text N4_AddressLine1
            {
                get
                {
                    return _n4_addressline1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N4_AddressLine1 item info.
            /// </summary>
            [RepositoryItemInfo("1af0cf8a-add1-4231-b5f1-30b0b98e54bc")]
            public virtual RepoItemInfo N4_AddressLine1Info
            {
                get
                {
                    return _n4_addressline1Info;
                }
            }

            /// <summary>
            /// The N6_County item.
            /// </summary>
            [RepositoryItem("a2356b3e-3868-43fe-98f0-6f472571d288")]
            public virtual Ranorex.Text N6_County
            {
                get
                {
                    return _n6_countyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N6_County item info.
            /// </summary>
            [RepositoryItemInfo("a2356b3e-3868-43fe-98f0-6f472571d288")]
            public virtual RepoItemInfo N6_CountyInfo
            {
                get
                {
                    return _n6_countyInfo;
                }
            }

            /// <summary>
            /// The N5_AddressLine2 item.
            /// </summary>
            [RepositoryItem("7676bef3-0cdc-48fa-a1ae-9db4f5374501")]
            public virtual Ranorex.Text N5_AddressLine2
            {
                get
                {
                    return _n5_addressline2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N5_AddressLine2 item info.
            /// </summary>
            [RepositoryItemInfo("7676bef3-0cdc-48fa-a1ae-9db4f5374501")]
            public virtual RepoItemInfo N5_AddressLine2Info
            {
                get
                {
                    return _n5_addressline2Info;
                }
            }

            /// <summary>
            /// The N3_Name item.
            /// </summary>
            [RepositoryItem("9c9d1a09-92fd-4aa8-aa76-708ddd2394f8")]
            public virtual Ranorex.Text N3_Name
            {
                get
                {
                    return _n3_nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N3_Name item info.
            /// </summary>
            [RepositoryItemInfo("9c9d1a09-92fd-4aa8-aa76-708ddd2394f8")]
            public virtual RepoItemInfo N3_NameInfo
            {
                get
                {
                    return _n3_nameInfo;
                }
            }

            /// <summary>
            /// The N2_ConfirmEmail item.
            /// </summary>
            [RepositoryItem("84998ed8-d795-4e50-8cbb-a510e394bc9d")]
            public virtual Ranorex.Text N2_ConfirmEmail
            {
                get
                {
                    return _n2_confirmemailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N2_ConfirmEmail item info.
            /// </summary>
            [RepositoryItemInfo("84998ed8-d795-4e50-8cbb-a510e394bc9d")]
            public virtual RepoItemInfo N2_ConfirmEmailInfo
            {
                get
                {
                    return _n2_confirmemailInfo;
                }
            }

            /// <summary>
            /// The N1_Email item.
            /// </summary>
            [RepositoryItem("52d5e7d4-3dda-48d2-88cd-62be1cf1a24f")]
            public virtual Ranorex.Text N1_Email
            {
                get
                {
                    return _n1_emailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N1_Email item info.
            /// </summary>
            [RepositoryItemInfo("52d5e7d4-3dda-48d2-88cd-62be1cf1a24f")]
            public virtual RepoItemInfo N1_EmailInfo
            {
                get
                {
                    return _n1_emailInfo;
                }
            }

            /// <summary>
            /// The Warning_PostcodeInvalid item.
            /// </summary>
            [RepositoryItem("4ef175d3-3430-4e89-b63c-1b16b5d86570")]
            public virtual Ranorex.Text Warning_PostcodeInvalid
            {
                get
                {
                    return _warning_postcodeinvalidInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Warning_PostcodeInvalid item info.
            /// </summary>
            [RepositoryItemInfo("4ef175d3-3430-4e89-b63c-1b16b5d86570")]
            public virtual RepoItemInfo Warning_PostcodeInvalidInfo
            {
                get
                {
                    return _warning_postcodeinvalidInfo;
                }
            }

            /// <summary>
            /// The N8_Country item.
            /// </summary>
            [RepositoryItem("335bac03-6c35-443f-be1d-4b8a96ee6875")]
            public virtual Ranorex.ComboBox N8_Country
            {
                get
                {
                    return _n8_countryInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The N8_Country item info.
            /// </summary>
            [RepositoryItemInfo("335bac03-6c35-443f-be1d-4b8a96ee6875")]
            public virtual RepoItemInfo N8_CountryInfo
            {
                get
                {
                    return _n8_countryInfo;
                }
            }

            /// <summary>
            /// The Button_SaveShipping item.
            /// </summary>
            [RepositoryItem("f1faeefc-46df-4328-8301-69bf333f65e5")]
            public virtual Ranorex.Button Button_SaveShipping
            {
                get
                {
                    return _button_saveshippingInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_SaveShipping item info.
            /// </summary>
            [RepositoryItemInfo("f1faeefc-46df-4328-8301-69bf333f65e5")]
            public virtual RepoItemInfo Button_SaveShippingInfo
            {
                get
                {
                    return _button_saveshippingInfo;
                }
            }

            /// <summary>
            /// The Header_DELIVERYLOCATION item.
            /// </summary>
            [RepositoryItem("ee1796a5-c189-490b-ba8a-857f18fb67b5")]
            public virtual Ranorex.Text Header_DELIVERYLOCATION
            {
                get
                {
                    return _header_deliverylocationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header_DELIVERYLOCATION item info.
            /// </summary>
            [RepositoryItemInfo("ee1796a5-c189-490b-ba8a-857f18fb67b5")]
            public virtual RepoItemInfo Header_DELIVERYLOCATIONInfo
            {
                get
                {
                    return _header_deliverylocationInfo;
                }
            }
        }

        /// <summary>
        /// The Page3_Shipping_SpecificationFolder folder.
        /// </summary>
        [RepositoryFolder("8240971d-4b89-46b0-8563-1dcf082fcbda")]
        public partial class Page3_Shipping_SpecificationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button_continueInfo;
            RepoItemInfo _header_shippingspecificationInfo;

            /// <summary>
            /// Creates a new Page3_Shipping_Specification  folder.
            /// </summary>
            public Page3_Shipping_SpecificationFolder(RepoGenBaseFolder parentFolder) :
                    base("Page3_Shipping_Specification", "", parentFolder, 0, null, false, "8240971d-4b89-46b0-8563-1dcf082fcbda", "")
            {
                _button_continueInfo = new RepoItemInfo(this, "Button_Continue", "element[2]/element[2]/element[@accessiblerole='None']/element[2]/button[@accessiblename='Continue']", 30000, null, "d64453d0-63a2-4082-8ab5-7a9a0edc13de");
                _header_shippingspecificationInfo = new RepoItemInfo(this, "Header_SHIPPINGSPECIFICATION", ".//text[@accessiblename='SHIPPING SPECIFICATION']", 30000, null, "0be90b22-a3f0-4d7d-8763-6706523e1595");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8240971d-4b89-46b0-8563-1dcf082fcbda")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button_Continue item.
            /// </summary>
            [RepositoryItem("d64453d0-63a2-4082-8ab5-7a9a0edc13de")]
            public virtual Ranorex.Button Button_Continue
            {
                get
                {
                    return _button_continueInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_Continue item info.
            /// </summary>
            [RepositoryItemInfo("d64453d0-63a2-4082-8ab5-7a9a0edc13de")]
            public virtual RepoItemInfo Button_ContinueInfo
            {
                get
                {
                    return _button_continueInfo;
                }
            }

            /// <summary>
            /// The Header_SHIPPINGSPECIFICATION item.
            /// </summary>
            [RepositoryItem("0be90b22-a3f0-4d7d-8763-6706523e1595")]
            public virtual Ranorex.Text Header_SHIPPINGSPECIFICATION
            {
                get
                {
                    return _header_shippingspecificationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header_SHIPPINGSPECIFICATION item info.
            /// </summary>
            [RepositoryItemInfo("0be90b22-a3f0-4d7d-8763-6706523e1595")]
            public virtual RepoItemInfo Header_SHIPPINGSPECIFICATIONInfo
            {
                get
                {
                    return _header_shippingspecificationInfo;
                }
            }
        }

        /// <summary>
        /// The Page4_Payment_DetailsFolder folder.
        /// </summary>
        [RepositoryFolder("20c9cd1b-9237-4c21-8854-7cee4a220dbc")]
        public partial class Page4_Payment_DetailsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _n1_cardtypeInfo;
            RepoItemInfo _n2_cardnumberInfo;
            RepoItemInfo _warning_cardnumberhascharactersInfo;
            RepoItemInfo _warning_cardnumbertooshortInfo;
            RepoItemInfo _info_totalamounttextInfo;
            RepoItemInfo _button_completepurchaseInfo;
            RepoItemInfo _header_paymentdetailsInfo;

            /// <summary>
            /// Creates a new Page4_Payment_Details  folder.
            /// </summary>
            public Page4_Payment_DetailsFolder(RepoGenBaseFolder parentFolder) :
                    base("Page4_Payment_Details", "", parentFolder, 0, null, false, "20c9cd1b-9237-4c21-8854-7cee4a220dbc", "")
            {
                _n1_cardtypeInfo = new RepoItemInfo(this, "N1_CardType", ".//container[@accessiblerole='Grouping']/element[1]/combobox[@accessiblerole='ComboBox']", 30000, null, "1946b140-35e6-4029-bfbd-48272c769e4a");
                _n2_cardnumberInfo = new RepoItemInfo(this, "N2_CardNumber", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename='Name']", 30000, null, "b840dcdd-31b6-4314-86e5-9f3af335d6bf");
                _warning_cardnumberhascharactersInfo = new RepoItemInfo(this, "Warning_CardNumberHasCharacters", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename~'^The\\ card\\ number\\ can\\ only\\ ']", 30000, null, "c1666094-c05b-469c-b436-d43d10a9614d");
                _warning_cardnumbertooshortInfo = new RepoItemInfo(this, "Warning_CardNumberTooShort", ".//container[@accessiblerole='Grouping']/element[2]/text[@accessiblename~'^The\\ Card\\ Number\\ cannot\\ ha']", 30000, null, "3b79d7df-68bc-4393-9e10-e36cb4a2cfa0");
                _info_totalamounttextInfo = new RepoItemInfo(this, "Info_TotalAmountText", ".//container[@accessiblerole='Grouping']/element[3]/text[@accessiblename='857.00']", 30000, null, "0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd");
                _button_completepurchaseInfo = new RepoItemInfo(this, "Button_CompletePurchase", "element[2]/element[2]//button[@accessiblename='Complete Purchase']", 30000, null, "8d98b018-7c02-4b36-882e-c2bbe3638439");
                _header_paymentdetailsInfo = new RepoItemInfo(this, "Header_PAYMENTDETAILS", ".//text[@accessiblename='PAYMENT DETAILS']", 30000, null, "0a52e7a9-1a16-4049-9056-13af83bffa37");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20c9cd1b-9237-4c21-8854-7cee4a220dbc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The N1_CardType item.
            /// </summary>
            [RepositoryItem("1946b140-35e6-4029-bfbd-48272c769e4a")]
            public virtual Ranorex.ComboBox N1_CardType
            {
                get
                {
                    return _n1_cardtypeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The N1_CardType item info.
            /// </summary>
            [RepositoryItemInfo("1946b140-35e6-4029-bfbd-48272c769e4a")]
            public virtual RepoItemInfo N1_CardTypeInfo
            {
                get
                {
                    return _n1_cardtypeInfo;
                }
            }

            /// <summary>
            /// The N2_CardNumber item.
            /// </summary>
            [RepositoryItem("b840dcdd-31b6-4314-86e5-9f3af335d6bf")]
            public virtual Ranorex.Text N2_CardNumber
            {
                get
                {
                    return _n2_cardnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The N2_CardNumber item info.
            /// </summary>
            [RepositoryItemInfo("b840dcdd-31b6-4314-86e5-9f3af335d6bf")]
            public virtual RepoItemInfo N2_CardNumberInfo
            {
                get
                {
                    return _n2_cardnumberInfo;
                }
            }

            /// <summary>
            /// The Warning_CardNumberHasCharacters item.
            /// </summary>
            [RepositoryItem("c1666094-c05b-469c-b436-d43d10a9614d")]
            public virtual Ranorex.Text Warning_CardNumberHasCharacters
            {
                get
                {
                    return _warning_cardnumberhascharactersInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Warning_CardNumberHasCharacters item info.
            /// </summary>
            [RepositoryItemInfo("c1666094-c05b-469c-b436-d43d10a9614d")]
            public virtual RepoItemInfo Warning_CardNumberHasCharactersInfo
            {
                get
                {
                    return _warning_cardnumberhascharactersInfo;
                }
            }

            /// <summary>
            /// The Warning_CardNumberTooShort item.
            /// </summary>
            [RepositoryItem("3b79d7df-68bc-4393-9e10-e36cb4a2cfa0")]
            public virtual Ranorex.Text Warning_CardNumberTooShort
            {
                get
                {
                    return _warning_cardnumbertooshortInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Warning_CardNumberTooShort item info.
            /// </summary>
            [RepositoryItemInfo("3b79d7df-68bc-4393-9e10-e36cb4a2cfa0")]
            public virtual RepoItemInfo Warning_CardNumberTooShortInfo
            {
                get
                {
                    return _warning_cardnumbertooshortInfo;
                }
            }

            /// <summary>
            /// The Info_TotalAmountText item.
            /// </summary>
            [RepositoryItem("0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd")]
            public virtual Ranorex.Text Info_TotalAmountText
            {
                get
                {
                    return _info_totalamounttextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Info_TotalAmountText item info.
            /// </summary>
            [RepositoryItemInfo("0e8be4e5-a2d6-4bc7-9f85-634f6f5f17fd")]
            public virtual RepoItemInfo Info_TotalAmountTextInfo
            {
                get
                {
                    return _info_totalamounttextInfo;
                }
            }

            /// <summary>
            /// The Button_CompletePurchase item.
            /// </summary>
            [RepositoryItem("8d98b018-7c02-4b36-882e-c2bbe3638439")]
            public virtual Ranorex.Button Button_CompletePurchase
            {
                get
                {
                    return _button_completepurchaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_CompletePurchase item info.
            /// </summary>
            [RepositoryItemInfo("8d98b018-7c02-4b36-882e-c2bbe3638439")]
            public virtual RepoItemInfo Button_CompletePurchaseInfo
            {
                get
                {
                    return _button_completepurchaseInfo;
                }
            }

            /// <summary>
            /// The Header_PAYMENTDETAILS item.
            /// </summary>
            [RepositoryItem("0a52e7a9-1a16-4049-9056-13af83bffa37")]
            public virtual Ranorex.Text Header_PAYMENTDETAILS
            {
                get
                {
                    return _header_paymentdetailsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header_PAYMENTDETAILS item info.
            /// </summary>
            [RepositoryItemInfo("0a52e7a9-1a16-4049-9056-13af83bffa37")]
            public virtual RepoItemInfo Header_PAYMENTDETAILSInfo
            {
                get
                {
                    return _header_paymentdetailsInfo;
                }
            }
        }

        /// <summary>
        /// The Page5_Order_FinalisedFolder folder.
        /// </summary>
        [RepositoryFolder("b80788e5-e019-415e-b9a8-6349a4b942af")]
        public partial class Page5_Order_FinalisedFolder : RepoGenBaseFolder
        {
            RepoItemInfo _orderfinalisedInfo;
            RepoItemInfo _info_estimateddeliverytimeInfo;
            RepoItemInfo _info_totalcostInfo;

            /// <summary>
            /// Creates a new Page5_Order_Finalised  folder.
            /// </summary>
            public Page5_Order_FinalisedFolder(RepoGenBaseFolder parentFolder) :
                    base("Page5_Order_Finalised", "", parentFolder, 0, null, false, "b80788e5-e019-415e-b9a8-6349a4b942af", "")
            {
                _orderfinalisedInfo = new RepoItemInfo(this, "ORDERFINALISED", "element[2]/element[1]/text[@accessiblename='ORDER FINALISED']", 30000, null, "768b928b-66b4-43f7-969c-e2880441fd91");
                _info_estimateddeliverytimeInfo = new RepoItemInfo(this, "Info_EstimatedDeliveryTime", "element[2]/element[2]/text[@accessiblename~'^Estimated\\ delivery\\ time\\ -']", 30000, null, "0e74daed-82a6-4f0a-bd9e-751f18c1e7d9");
                _info_totalcostInfo = new RepoItemInfo(this, "Info_TotalCost", "element[2]/element[3]/text[@accessiblename='Total cost: 855.00']", 30000, null, "583399b2-5689-4d80-afeb-9ee93527c50b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b80788e5-e019-415e-b9a8-6349a4b942af")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ORDERFINALISED item.
            /// </summary>
            [RepositoryItem("768b928b-66b4-43f7-969c-e2880441fd91")]
            public virtual Ranorex.Text ORDERFINALISED
            {
                get
                {
                    return _orderfinalisedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ORDERFINALISED item info.
            /// </summary>
            [RepositoryItemInfo("768b928b-66b4-43f7-969c-e2880441fd91")]
            public virtual RepoItemInfo ORDERFINALISEDInfo
            {
                get
                {
                    return _orderfinalisedInfo;
                }
            }

            /// <summary>
            /// The Info_EstimatedDeliveryTime item.
            /// </summary>
            [RepositoryItem("0e74daed-82a6-4f0a-bd9e-751f18c1e7d9")]
            public virtual Ranorex.Text Info_EstimatedDeliveryTime
            {
                get
                {
                    return _info_estimateddeliverytimeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Info_EstimatedDeliveryTime item info.
            /// </summary>
            [RepositoryItemInfo("0e74daed-82a6-4f0a-bd9e-751f18c1e7d9")]
            public virtual RepoItemInfo Info_EstimatedDeliveryTimeInfo
            {
                get
                {
                    return _info_estimateddeliverytimeInfo;
                }
            }

            /// <summary>
            /// The Info_TotalCost item.
            /// </summary>
            [RepositoryItem("583399b2-5689-4d80-afeb-9ee93527c50b")]
            public virtual Ranorex.Text Info_TotalCost
            {
                get
                {
                    return _info_totalcostInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Info_TotalCost item info.
            /// </summary>
            [RepositoryItemInfo("583399b2-5689-4d80-afeb-9ee93527c50b")]
            public virtual RepoItemInfo Info_TotalCostInfo
            {
                get
                {
                    return _info_totalcostInfo;
                }
            }
        }

        /// <summary>
        /// The Page_AboutPageFolder folder.
        /// </summary>
        [RepositoryFolder("6bb127cd-365b-4549-834e-b301159eca55")]
        public partial class Page_AboutPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _header_aboutInfo;

            /// <summary>
            /// Creates a new Page_AboutPage  folder.
            /// </summary>
            public Page_AboutPageFolder(RepoGenBaseFolder parentFolder) :
                    base("Page_AboutPage", "", parentFolder, 0, null, false, "6bb127cd-365b-4549-834e-b301159eca55", "")
            {
                _header_aboutInfo = new RepoItemInfo(this, "Header_ABOUT", ".//text[@accessiblename='GAME RULES']", 30000, null, "22bcff07-345f-41ef-8a77-c487cbd29418");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6bb127cd-365b-4549-834e-b301159eca55")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Header_ABOUT item.
            /// </summary>
            [RepositoryItem("22bcff07-345f-41ef-8a77-c487cbd29418")]
            public virtual Ranorex.Text Header_ABOUT
            {
                get
                {
                    return _header_aboutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Header_ABOUT item info.
            /// </summary>
            [RepositoryItemInfo("22bcff07-345f-41ef-8a77-c487cbd29418")]
            public virtual RepoItemInfo Header_ABOUTInfo
            {
                get
                {
                    return _header_aboutInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("3822d8cf-2452-481b-886b-8e757896e2f0")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "3822d8cf-2452-481b-886b-8e757896e2f0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3822d8cf-2452-481b-886b-8e757896e2f0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3822d8cf-2452-481b-886b-8e757896e2f0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}