///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WEBSTORE_RANOREX
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("427a842c-6217-4a85-b482-6cbf2f6787cc", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WEBSTORE_RANOREXRepository repository.
        /// </summary>
        public static WEBSTORE_RANOREXRepository repo = WEBSTORE_RANOREXRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://grid-tools-downloads.com/Will/TMF/index.php' with browser 'firefox' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://grid-tools-downloads.com/Will/TMF/index.php", "firefox", "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='PRODUCT CATALOG') on item 'MozillaFirefox.WebStore.Page1_Product_Catalog.Header_PRODUCTCATALOG'.", repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Header_PRODUCTCATALOGInfo, "AccessibleName", "PRODUCT CATALOG");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='-- Select a product --') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, "Text", "-- Select a product --");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType' at 217;21.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, new RecordItemIndex(3));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType.Click("217;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 208;24.", repo.Dropdown.SelfInfo, new RecordItemIndex(4));
            repo.Dropdown.Self.Click("208;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='850.00') on item 'MozillaFirefox.WebStore.Text85000'.", repo.MozillaFirefox.WebStore.Text85000Info, new RecordItemIndex(5));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Text85000Info, "AccessibleName", "850.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Order Product') on item 'MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProduct'.", repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProductInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProductInfo, "Text", "Order Product");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProduct' at 26;24.", repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProductInfo, new RecordItemIndex(7));
            repo.MozillaFirefox.WebStore.Page1_Product_Catalog.Button_OrderProduct.Click("26;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='DELIVERY LOCATION') on item 'MozillaFirefox.WebStore.Page2_Delivery_Location.Header_DELIVERYLOCATION'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Header_DELIVERYLOCATIONInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Header_DELIVERYLOCATIONInfo, "AccessibleName", "DELIVERY LOCATION");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N1_Email' at 51;18.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(9));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N1_Email.Click("51;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'guawi01{LShiftKey down}@{LShiftKey up}ca.com{Tab}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N1_Email'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N1_EmailInfo, new RecordItemIndex(10));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N1_Email.PressKeys("guawi01{LShiftKey down}@{LShiftKey up}ca.com{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmail' at 34;14.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(11));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmail.Click("34;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'guawi01{LShiftKey down}@{LShiftKey up}ca.com' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmail'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmailInfo, new RecordItemIndex(12));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N2_ConfirmEmail.PressKeys("guawi01{LShiftKey down}@{LShiftKey up}ca.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N3_Name' at 37;10.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(13));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N3_Name.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bill{Tab}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N3_Name'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N3_NameInfo, new RecordItemIndex(14));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N3_Name.PressKeys("bill{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1' at 31;24.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(15));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1.Click("31;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10{Space}{RShiftKey down}R{RShiftKey up}oad{Space}{RShiftKey down}R{RShiftKey up}oad{Tab}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1Info, new RecordItemIndex(16));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N4_AddressLine1.PressKeys("10{Space}{RShiftKey down}R{RShiftKey up}oad{Space}{RShiftKey down}R{RShiftKey up}oad{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2' at 27;15.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2Info, new RecordItemIndex(17));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2.Click("27;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey}{LShiftKey down}P{LShiftKey up}lace' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2Info, new RecordItemIndex(18));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N5_AddressLine2.PressKeys("{RShiftKey}{LShiftKey down}P{LShiftKey up}lace");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N6_County' at 33;8.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N6_CountyInfo, new RecordItemIndex(19));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N6_County.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}P{LShiftKey up}laceshire' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N6_County'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N6_CountyInfo, new RecordItemIndex(20));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N6_County.PressKeys("{LShiftKey down}P{LShiftKey up}laceshire");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode' at 22;30.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(21));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.Click("22;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}P{LShiftKey up}{LShiftKey down}L{LShiftKey up}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(22));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("{LShiftKey down}P{LShiftKey up}{LShiftKey down}L{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '7' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(23));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(24));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey up}{LShiftKey down}J{LShiftKey up}98' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(25));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("{LShiftKey up}{LShiftKey down}J{LShiftKey up}98");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N8_Country' at 62;27.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N8_CountryInfo, new RecordItemIndex(26));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N8_Country.Click("62;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 35;46.", repo.Dropdown.SelfInfo, new RecordItemIndex(27));
            repo.Dropdown.Self.Click("35;46");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save Shipping') on item 'MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShipping'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShippingInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShippingInfo, "Text", "Save Shipping");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShipping' at 28;8.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShippingInfo, new RecordItemIndex(29));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShipping.Click("28;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode' at 51;27.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(30));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.DoubleClick("51;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode' at 62;12.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(31));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.Click("62;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode' at 62;12.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(32));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.DoubleClick("62;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Please enter a valid UK postcode (OX294TP is a valid UK postcode)') on item 'MozillaFirefox.WebStore.Page2_Delivery_Location.Warning_PostcodeInvalid'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Warning_PostcodeInvalidInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Warning_PostcodeInvalidInfo, "AccessibleName", "Please enter a valid UK postcode (OX294TP is a valid UK postcode)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode' at 74;11.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(34));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.Click("74;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{LShiftKey down}OX{LShiftKey up}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(35));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("{LControlKey}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{LShiftKey down}OX{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '294{LShiftKey down}TP{LShiftKey up}' with focus on 'MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode'.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCodeInfo, new RecordItemIndex(36));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.N7_PostCode.PressKeys("294{LShiftKey down}TP{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShipping' at 52;15.", repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShippingInfo, new RecordItemIndex(37));
            repo.MozillaFirefox.WebStore.Page2_Delivery_Location.Button_SaveShipping.Click("52;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='SHIPPING SPECIFICATION') on item 'MozillaFirefox.WebStore.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATION'.", repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATIONInfo, new RecordItemIndex(38));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Header_SHIPPINGSPECIFICATIONInfo, "AccessibleName", "SHIPPING SPECIFICATION");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Continue') on item 'MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_Continue'.", repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_ContinueInfo, new RecordItemIndex(39));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_ContinueInfo, "Text", "Continue");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_Continue' at 45;7.", repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_ContinueInfo, new RecordItemIndex(40));
            repo.MozillaFirefox.WebStore.Page3_Shipping_Specification.Button_Continue.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='PAYMENT DETAILS') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.Header_PAYMENTDETAILS'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Header_PAYMENTDETAILSInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.Header_PAYMENTDETAILSInfo, "AccessibleName", "PAYMENT DETAILS");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='-- Select Card Type --') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, new RecordItemIndex(42));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, "Text", "-- Select Card Type --");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType' at 148;27.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardTypeInfo, new RecordItemIndex(43));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N1_CardType.Click("148;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 115;32.", repo.Dropdown.SelfInfo, new RecordItemIndex(44));
            repo.Dropdown.Self.Click("115;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(45));
            Validate.Exists(repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber' at 122;11.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(46));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.Click("122;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111' with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(47));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.PressKeys("1111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase' at 64;15.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchaseInfo, new RecordItemIndex(48));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase.Click("64;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The Card Number cannot have less that 16 characters. ') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShort'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShortInfo, new RecordItemIndex(49));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShortInfo, "AccessibleName", "The Card Number cannot have less that 16 characters. ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber' at 84;25.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(50));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.DoubleClick("84;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber' at 84;25.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(51));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.Click("84;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(52));
            Keyboard.PrepareFocus(repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, 93, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999999999999' with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(53));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.PressKeys("9999999999999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase' at 84;24.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchaseInfo, new RecordItemIndex(54));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase.Click("84;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The Card Number cannot have more that 16 characters. ') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShort'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShortInfo, new RecordItemIndex(55));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberTooShortInfo, "AccessibleName", "The Card Number cannot have more that 16 characters. ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber' at 67;22.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(56));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.DoubleClick("67;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(57));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaaaaaaaaaaaaaaa' with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(58));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.PressKeys("aaaaaaaaaaaaaaaa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase' at 61;17.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchaseInfo, new RecordItemIndex(59));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase.Click("61;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The card number can only contain numbers.') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberHasCharacters'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberHasCharactersInfo, new RecordItemIndex(60));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.Warning_CardNumberHasCharactersInfo, "AccessibleName", "The card number can only contain numbers.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber' at 166;26.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(61));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.DoubleClick("166;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1111222233334444' with focus on 'MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumberInfo, new RecordItemIndex(62));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.N2_CardNumber.PressKeys("1111222233334444");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='857.00') on item 'MozillaFirefox.WebStore.Page4_Payment_Details.Info_TotalAmountText'.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Info_TotalAmountTextInfo, new RecordItemIndex(63));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page4_Payment_Details.Info_TotalAmountTextInfo, "AccessibleName", "857.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase' at 95;27.", repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchaseInfo, new RecordItemIndex(64));
            repo.MozillaFirefox.WebStore.Page4_Payment_Details.Button_CompletePurchase.Click("95;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Estimated delivery time - 4.5 days ') on item 'MozillaFirefox.WebStore.Page5_Order_Finalised.Info_EstimatedDeliveryTime'.", repo.MozillaFirefox.WebStore.Page5_Order_Finalised.Info_EstimatedDeliveryTimeInfo, new RecordItemIndex(65));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page5_Order_Finalised.Info_EstimatedDeliveryTimeInfo, "AccessibleName", "Estimated delivery time - 4.5 days ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Total cost: 855.00') on item 'MozillaFirefox.WebStore.Page5_Order_Finalised.Info_TotalCost'.", repo.MozillaFirefox.WebStore.Page5_Order_Finalised.Info_TotalCostInfo, new RecordItemIndex(66));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page5_Order_Finalised.Info_TotalCostInfo, "AccessibleName", "Total cost: 855.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='ORDER FINALISED') on item 'MozillaFirefox.WebStore.Page5_Order_Finalised.ORDERFINALISED'.", repo.MozillaFirefox.WebStore.Page5_Order_Finalised.ORDERFINALISEDInfo, new RecordItemIndex(67));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page5_Order_Finalised.ORDERFINALISEDInfo, "AccessibleName", "ORDER FINALISED");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='HOME') on item 'MozillaFirefox.WebStore.HOME'.", repo.MozillaFirefox.WebStore.HOMEInfo, new RecordItemIndex(68));
            Validate.Attribute(repo.MozillaFirefox.WebStore.HOMEInfo, "Text", "HOME");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='ABOUT') on item 'MozillaFirefox.WebStore.ABOUT'.", repo.MozillaFirefox.WebStore.ABOUTInfo, new RecordItemIndex(69));
            Validate.Attribute(repo.MozillaFirefox.WebStore.ABOUTInfo, "Text", "ABOUT");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.HttpGridToolsDownloadsComWillTMF' at 1256;852.", repo.MozillaFirefox.WebStore.HttpGridToolsDownloadsComWillTMFInfo, new RecordItemIndex(70));
            repo.MozillaFirefox.WebStore.HttpGridToolsDownloadsComWillTMF.Click("1256;852");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.ABOUT1' at 15;11.", repo.MozillaFirefox.WebStore.ABOUT1Info, new RecordItemIndex(71));
            repo.MozillaFirefox.WebStore.ABOUT1.Click("15;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='GAME RULES') on item 'MozillaFirefox.WebStore.Page_AboutPage.Header_ABOUT'.", repo.MozillaFirefox.WebStore.Page_AboutPage.Header_ABOUTInfo, new RecordItemIndex(72));
            Validate.Attribute(repo.MozillaFirefox.WebStore.Page_AboutPage.Header_ABOUTInfo, "AccessibleName", "GAME RULES");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.WebStore.HOME' at 38;26.", repo.MozillaFirefox.WebStore.HOMEInfo, new RecordItemIndex(73));
            repo.MozillaFirefox.WebStore.HOME.Click("38;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
